### ISSUE TITLE
Could not import PyQt5 but the package is in conda list

### ISSUE THREAD

**Issue by enazbngl** [Valdes-Tresanco-MS/gmx_MMPBSA#100]
Dear All,

I was trying to install the gmx_MMPBSA and encountered several problems which I was able to solve following [this thread](https://groups.google.com/g/gmx_mmpbsa/c/wLll2_ueTIw). 
After installation, I have encountered another problem when running **gmx_MMPBSA_ana** concerning **PyQt5**. When I check the package list with "conda list" i can see pyqt5 is already installed. The error is as follows:

> [INFO   ] Opening gmx_MMPBSA_ana...
ERROR:root:MMPBSA_Error Could not import PyQt5. gmx_MMPBSA_ana will be disabled until you install it.
           Check the gmx_MMPBSA.log file to report the problem.
Traceback (most recent call last):
  File "/home/enaz/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 115, in gmxmmpbsa_ana
    from GMXMMPBSA.analyzer.gui import GMX_MMPBSA_ANA
  File "/home/enaz/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py", line 29, in <module>
    from GMXMMPBSA.analyzer.plots import Charts
  File "/home/enaz/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/GMXMMPBSA/analyzer/plots.py", line 29, in <module>
    import seaborn as sns
  File "/home/enaz/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/seaborn/__init__.py", line 2, in <module>
    from .rcmod import *  # noqa: F401,F403
  File "/home/enaz/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/seaborn/rcmod.py", line 7, in <module>
    from . import palettes
  File "/home/enaz/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/seaborn/palettes.py", line 9, in <module>
    from .utils import desaturate, get_color_cycle
  File "/home/enaz/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/seaborn/utils.py", line 10, in <module>
    from scipy import stats
  File "/home/enaz/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/enaz/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/enaz/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/enaz/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/enaz/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/scipy/optimize/__init__.py", line 400, in <module>
    from .optimize import *
  File "/home/enaz/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/scipy/optimize/optimize.py", line 36, in <module>
    from ._numdiff import approx_derivative
  File "/home/enaz/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/scipy/optimize/_numdiff.py", line 8, in <module>
    from ._group_columns import group_dense, group_sparse
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/enaz/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/scipy/optimize/_group_columns.cpython-39-x86_64-linux-gnu.so)

> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/enaz/anaconda3/envs/AmberTools21/bin/gmx_MMPBSA_ana", line 8, in <module>
>     sys.exit(gmxmmpbsa_ana())
>   File "/home/enaz/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 118, in gmxmmpbsa_ana
>     GMXMMPBSA_ERROR('Could not import PyQt5. gmx_MMPBSA_ana will be disabled until you install it')
>   File "/home/enaz/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 169, in __init__
>     raise exc(msg + '. Check the gmx_MMPBSA.log file to report the problem.')
> GMXMMPBSA.exceptions.MMPBSA_Error: Could not import PyQt5. gmx_MMPBSA_ana will be disabled until you install it. Check the gmx_MMPBSA.log file to report the problem.

The log file and the output of the "conda list" are attached.

[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7661263/gmx_MMPBSA.log)
[condalist.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7661279/condalist.txt)

**Comment by Valdes-Tresanco-MS** [comment]
I think the error is due to this `ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version GLIBCXX_3.4.26 not found`, only that it is reported associated with `PyQt5` because we have a bad traceback design (which we will write down to improve it).
Let's do some tests to be sure. Please run in a terminal
`sudo apt install libstdc ++ 6`

In case it doesn't work, open a new terminal, activate the conda environment you are working in, and run `python`
Once in the python console type import `PyQt5` and show me the output.

Mario S.

**Comment by enazbngl** [comment]
Dear Mario,

Thank you for such a quick response. I've tried your suggestions. The first
one did not work. The output for  "sudo apt install libstdc ++ 6" was:

Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> libstdc++6 is already the newest version (8.4.0-1ubuntu1~18.04).
> 0 upgraded, 0 newly installed, 0 to remove and 80 not upgraded.


"Import PyQt5" from the python console was successful. So, there was no
output.

I've tried installing it on another workstation and everything works just
fine. But this one was not attended for a while. Maybe an upgrade will
solve the problems.

Regards,

Elif Naz BINGOL

Computational Biology and Bioinformatics Research Group
Marmara University, Department of Bioengineering
Goztepe Campus 34722
Istanbul - Turkey

**Comment by Valdes-Tresanco-MS** [comment]
Ok, please show me the output of this command `echo $PYTHONPATH`

**Comment by enazbngl** [comment]
It's empty. The output of echo $PATH:

/home/enaz/anaconda3/envs/AmberTools21/bin:/home/enaz/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin



Elif Naz BINGOL, PhD Student
Computational Biology and Bioinformatics Research Group
Marmara University, Department of Bioengineering
Goztepe Campus 34722
Istanbul - Turkey

**Comment by enazbngl** [comment]
Sorry for the delay. The package was already installed.

Elif Naz

**Comment by Valdes-Tresanco-MS** [comment]
Have you tried creating another conda environment, switching to a new conda version (with another python version), or a fresh conda installation?. It is that at the moment in all the tests that I have done it works correctly. If possible, send me as much information about your work environment to try to recreate it and identify the error

**Comment by Valdes-Tresanco-MS** [comment]
Closing as there is no activity
