### ISSUE TITLE
[Question]: Could not import PyQt5/PyQt6

### ISSUE THREAD

**Issue by wrmartin** [Valdes-Tresanco-MS/gmx_MMPBSA#208]
### Bug summary

I'm unable to run gmx_MMPBSA_ana. This is related to a closed issue, so apologies for the delay in the response. The suggestion to attempt a few imports results in the following:

### Terminal output

```bash
(gmxMMPBSA) [martinw3@lri-109709 WT_1]$ gmx_MMPBSA_ana
ERROR:root:MMPBSA_Error Could not import PyQt5/PyQt6. gmx_MMPBSA_ana will be disabled until you install it.
           Check the gmx_MMPBSA.log file to report the problem.
Traceback (most recent call last):
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA_ana", line 8, in <module>
    sys.exit(gmxmmpbsa_ana())
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 129, in gmxmmpbsa_ana
    GMXMMPBSA_ERROR('Could not import PyQt5/PyQt6. gmx_MMPBSA_ana will be disabled until you install it')
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 169, in __init__
    raise exc(msg + '\nCheck the gmx_MMPBSA.log file to report the problem.')
GMXMMPBSA.exceptions.MMPBSA_Error: Could not import PyQt5/PyQt6. gmx_MMPBSA_ana will be disabled until you install it
Check the gmx_MMPBSA.log file to report the problem.
(gmxMMPBSA) [martinw3@lri-109709 WT_1]$ echo $PYTHONPATH

(gmxMMPBSA) [martinw3@lri-109709 WT_1]$ which python
~/anaconda3/envs/gmxMMPBSA/bin/python
(gmxMMPBSA) [martinw3@lri-109709 WT_1]$ python
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt5
>>> from PyQt5.QtCore import QT_VERSION_STR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /lib64/libQt5Core.so.5: version `Qt_5.15' not found (required by /home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/PyQt5/QtCore.abi3.so)
>>> from PyQt5.Qt import PYQT_VERSION_STR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'PYQT_VERSION_STR' from 'PyQt5.Qt' (/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/PyQt5/Qt.abi3.so)
>>> exit()
```

### Actual outcome

The Qt version installed at a system level is 5.9.7. I'm not sure if there is any way I can overcome this; I haven't found a newer version for CentOS 7, so it's possible the solution is "use a more modern OS". I wasn't able to get PyQt6 to install.

### Expected outcome

Loading gmx_MMPBSA_ana :)

### Operating system

CentOS 7

### gmx_MMPBSA_ana Version

1.5.1

### Python version

3.9.7

### Installation

conda AmberTools + conda

**Comment by wrmartin** [comment]
That does allow it to run, yes. I do get the following, though:

`Traceback (most recent call last):
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/dialogs.py", line 360, in get_data
    self.parent.read_data(queue, self.options)
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py", line 986, in read_data
    gmx_mmpbsa_api.load_file(path)
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/API.py", line 76, in load_file
    self._get_fromH5(fname)
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/API.py", line 361, in _get_fromH5
    h5file = H5Output(h5file)
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/amber_outputs.py", line 1661, in __init__
    self._h52decomp(key)
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/amber_outputs.py", line 1729, in _h52decomp
    calc_types[key1][key2].parse_from_h5(self.h5f[key][key1][key2])
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/amber_outputs.py", line 1126, in parse_from_h5
    self[term][res][res_e][res2] = EnergyVector(d[term][res][res_e][res2][()])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 783, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 272, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 213, in h5py._selector.Selector.apply_args
TypeError: Simple selection can't process 36.278
Aborted (core dumped)
`
The data was generated using version v1.5.0+2.gc36d71b; is 1.5.1 not compatible or do I have another issue here?

**Comment by Valdes-Tresanco-MS** [comment]
The option to use the h5 file is not yet suitable for production. Since we are updating some calculation methods and data structures, this functionality is lagging ([here we clarify](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/input_file/#miscellaneous-options)). And at the moment, we are focused on implementing new features, so this is not in our immediate plans.
I hope you have done the calculations with the recommended options, otherwise, there is no way to get the stored results reliably. Sorry about that

**Comment by Valdes-Tresanco-MS** [comment]
Wow, that's a lot of memory. Can you give me an estimate of the number of atoms and variables you defined in the input file? 
We haven't tested **gmx_MMPBSA_ana** to those extremes.

**Comment by Valdes-Tresanco-MS** [comment]
In the new version, we created a different data storage system to be able to manage the change in the frame range. This system still needs to be improved to make it more efficient. If you can email me your system files (100 or 200 frames) to do some tests it can help. I will try to work on that as soon as possible.

After reviewing several sections on the performance, processing, and storage of a large dataset with pandas, I am going to open an issue to work on it.

**Comment by wrmartin** [comment]
I'll have to figure out a way to shrink and store some data to send.

**Comment by Valdes-Tresanco-MS** [comment]
I close this issue since the PyQt5 problem was solved. For the improvement of **gmx_MMPBSA_ana** I opened [this one](#209)
