### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by Byun-jinyoung** [Valdes-Tresanco-MS/gmx_MMPBSA#21]
**Describe the issue**
gmx_MMPBSA installation issue

**_If you will report an error, please complete this form_**
**To Reproduce**
```
$source home/byun/apps/AMBER/amber20_src/amber.sh
$conda activate /home/byun/apps/AMBER/amber20_src/miniconda
$which amber.python 
   > ~/apps/AMBER/amber20_src/bin/amber.python
$ amber.python -m pip install gmx_MMPBSA
```
When I prompted the lines above, I have encountered installation issue.  Below is the error message 

**Additional context**
```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting gmx_MMPBSA
  Using cached gmx_MMPBSA-1.3.1.tar.gz (510 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/byun/apps/AMBER/amber20_src/bin/amber.python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hmLq4m/gmx-mmpbsa/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hmLq4m/gmx-mmpbsa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-7_05IR
         cwd: /tmp/pip-install-hmLq4m/gmx-mmpbsa/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hmLq4m/gmx-mmpbsa/setup.py", line 20, in <module>
        import versioneer
      File "versioneer.py", line 1739
        file=sys.stderr)
            ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Valdes-Tresanco-MS** [comment]
gmx_MMPBSA only support python 3. Please, check the documentation [here](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/installation/#requirements) y see the badges [![python](https://img.shields.io/badge/python-v3.x-blue)]()

**Comment by Byun-jinyoung** [comment]
Because I installed amber20 with legacy configure file, I have amber.python version 2.7.
Does it okay when I change the symbolic link amber.python into another python?

**Comment by Valdes-Tresanco-MS** [comment]
I have not tested it. You may have problems later. As Python2 is no longer supported, we recommend installing amber with the `miniconda3` environment (it is installed by default).

**Comment by Valdes-Tresanco-MS** [comment]
@Byun-jinyoung Were you able to solve the problem?

**Comment by Byun-jinyoung** [comment]
I reinstalled amber20 with miniconda3 and python3
But I have encountered another problem and below is the gmx_MMPBSA.log 
```
[INFO   ] Started
[INFO   ] Loading and checking parameter files for compatibility...

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /opt/AMBER/amber20/bin/cpptraj
[INFO   ] tleap found! Using /opt/AMBER/amber20/bin/tleap
[INFO   ] parmchk2 found! Using /opt/AMBER/amber20/bin/parmchk2
[INFO   ] mmpbsa_py_energy found! Using /opt/AMBER/amber20/bin/mmpbsa_py_energy
[INFO   ] mmpbsa_py_nabnmode found! Using /opt/AMBER/amber20/bin/mmpbsa_py_nabnmode
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx_mpi found! Using /home/byun/apps/GROMACS/gromacs_cpu-2020.2_gcc-7.5.0_openmpi-4.0.2/bin/gmx_mpi
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER Topologies from GROMACS files...
[INFO   ] Checking if supported force fields exists in Amber data...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
                     :-) GROMACS - gmx make_ndx, 2020.2 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd    
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray     
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang  
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson    
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund   
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall   
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov  
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen 
 Christian Wennberg    Maarten Wolf      Artem Zhmurov   
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2019, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx make_ndx, version 2020.2
Executable:   /home/byun/apps/GROMACS/gromacs_cpu-2020.2_gcc-7.5.0_openmpi-4.0.2/bin/gmx_mpi
Data prefix:  /home/byun/apps/GROMACS/gromacs_cpu-2020.2_gcc-7.5.0_openmpi-4.0.2
Working dir:  /home/byun/PROject/CORONAMD/AMBER/CHARMM36-ff/X0072/amber/gmx_MMPBSA
Command line:
  gmx_mpi make_ndx -n index.ndx -o _GMXMMPBSA_COM_index.ndx


GROMACS reminds you: "Inventions have long since reached their limit, and I see no hope for further development." (Julius Sextus Frontinus, 1st century A.D.)

Going to read 1 old index file(s)
Counted atom numbers up to 90160 in index file

  0 System              : 90160 atoms
  1 Protein             :  4645 atoms
  2 Protein-H           :  2348 atoms
  3 C-alpha             :   304 atoms
  4 Backbone            :   912 atoms
  5 MainChain           :  1217 atoms
  6 MainChain+Cb        :  1495 atoms
  7 MainChain+H         :  1507 atoms
  8 SideChain           :  3138 atoms
  9 SideChain-H         :  1131 atoms
 10 Prot-Masses         :  4645 atoms
 11 non-Protein         : 85515 atoms
 12 Other               :    30 atoms
 13 LIG                 :    26 atoms
 14 POT                 :     4 atoms
 15 Water               : 85485 atoms
 16 SOL                 : 85485 atoms
 17 non-Water           :  4675 atoms
 18 Protein_LIG         :  4671 atoms
 19 Water_and_ions      : 85489 atoms

 nr : group      '!': not  'name' nr name   'splitch' nr    Enter: list groups
 'a': atom       '&': and  'del' nr         'splitres' nr   'l': list residues
 't': atom type  '|': or   'keep' nr        'splitat' nr    'h': help
 'r': residue              'res' nr         'chain' char
 "name": group             'case': case sensitive           'q': save and quit
 'ri': residue index

> 

> 

> 
Copied index group 1 'GMXMMPBSA_REC'
Copied index group 13 'GMXMMPBSA_LIG'
Merged two groups with OR: 4645 26 -> 4671

 20 GMXMMPBSA_REC_GMXMMPBSA_LIG:  4671 atoms

> 
[INFO   ] Normal Complex: Saving group 1_13 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
                     :-) GROMACS - gmx editconf, 2020.2 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd    
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray     
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang  
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson    
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund   
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall   
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov  
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen 
 Christian Wennberg    Maarten Wolf      Artem Zhmurov   
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2019, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx editconf, version 2020.2
Executable:   /home/byun/apps/GROMACS/gromacs_cpu-2020.2_gcc-7.5.0_openmpi-4.0.2/bin/gmx_mpi
Data prefix:  /home/byun/apps/GROMACS/gromacs_cpu-2020.2_gcc-7.5.0_openmpi-4.0.2
Working dir:  /home/byun/PROject/CORONAMD/AMBER/CHARMM36-ff/X0072/amber/gmx_MMPBSA
Command line:
  gmx_mpi editconf -f simulation.tpr -o _GMXMMPBSA_COM.pdb -n _GMXMMPBSA_COM_index.ndx

Reading file simulation.tpr, VERSION 2020.2 (single precision)
Reading file simulation.tpr, VERSION 2020.2 (single precision)

Select a group for output:
Group     0 (         System) has 90160 elements
Group     1 (  GMXMMPBSA_REC) has  4645 elements
Group     2 (      Protein-H) has  2348 elements
Group     3 (        C-alpha) has   304 elements
Group     4 (       Backbone) has   912 elements
Group     5 (      MainChain) has  1217 elements
Group     6 (   MainChain+Cb) has  1495 elements
Group     7 (    MainChain+H) has  1507 elements
Group     8 (      SideChain) has  3138 elements
Group     9 (    SideChain-H) has  1131 elements
Group    10 (    Prot-Masses) has  4645 elements
Group    11 (    non-Protein) has 85515 elements
Group    12 (          Other) has    30 elements
Group    13 (  GMXMMPBSA_LIG) has    26 elements
Group    14 (            POT) has     4 elements
Group    15 (          Water) has 85485 elements
Group    16 (            SOL) has 85485 elements
Group    17 (      non-Water) has  4675 elements
Group    18 (    Protein_LIG) has  4671 elements
Group    19 ( Water_and_ions) has 85489 elements
Group    20 (GMXMMPBSA_REC_GMXMMPBSA_LIG) has  4671 elements
Select a group: 
GROMACS reminds you: "Shake Yourself" (YES)

Note that major changes are planned in future for editconf, to improve usability and utility.
Read 90160 atoms
Volume: 891.722 nm^3, corresponds to roughly 401200 electrons
No velocities found
Selected 20: 'GMXMMPBSA_REC_GMXMMPBSA_LIG'
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Complex: Saving group 1 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
                     :-) GROMACS - gmx editconf, 2020.2 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd    
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray     
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang  
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson    
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund   
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall   
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov  
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen 
 Christian Wennberg    Maarten Wolf      Artem Zhmurov   
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2019, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx editconf, version 2020.2
Executable:   /home/byun/apps/GROMACS/gromacs_cpu-2020.2_gcc-7.5.0_openmpi-4.0.2/bin/gmx_mpi
Data prefix:  /home/byun/apps/GROMACS/gromacs_cpu-2020.2_gcc-7.5.0_openmpi-4.0.2
Working dir:  /home/byun/PROject/CORONAMD/AMBER/CHARMM36-ff/X0072/amber/gmx_MMPBSA
Command line:
  gmx_mpi editconf -f simulation.tpr -o _GMXMMPBSA_REC.pdb -n _GMXMMPBSA_COM_index.ndx

Reading file simulation.tpr, VERSION 2020.2 (single precision)
Reading file simulation.tpr, VERSION 2020.2 (single precision)

Select a group for output:
Group     0 (         System) has 90160 elements
Group     1 (  GMXMMPBSA_REC) has  4645 elements
Group     2 (      Protein-H) has  2348 elements
Group     3 (        C-alpha) has   304 elements
Group     4 (       Backbone) has   912 elements
Group     5 (      MainChain) has  1217 elements
Group     6 (   MainChain+Cb) has  1495 elements
Group     7 (    MainChain+H) has  1507 elements
Group     8 (      SideChain) has  3138 elements
Group     9 (    SideChain-H) has  1131 elements
Group    10 (    Prot-Masses) has  4645 elements
Group    11 (    non-Protein) has 85515 elements
Group    12 (          Other) has    30 elements
Group    13 (  GMXMMPBSA_LIG) has    26 elements
Group    14 (            POT) has     4 elements
Group    15 (          Water) has 85485 elements
Group    16 (            SOL) has 85485 elements
Group    17 (      non-Water) has  4675 elements
Group    18 (    Protein_LIG) has  4671 elements
Group    19 ( Water_and_ions) has 85489 elements
Group    20 (GMXMMPBSA_REC_GMXMMPBSA_LIG) has  4671 elements
Select a group: 
GROMACS reminds you: "The Path Of the Righteous Man is Beset On All Sides With the Iniquities Of the Selfish and the Tyranny Of Evil Men." (Pulp Fiction)

Note that major changes are planned in future for editconf, to improve usability and utility.
Read 90160 atoms
Volume: 891.722 nm^3, corresponds to roughly 401200 electrons
No velocities found
Selected 1: 'GMXMMPBSA_REC'
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal ligand: Saving group 13 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
                     :-) GROMACS - gmx editconf, 2020.2 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd    
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray     
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang  
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson    
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund   
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall   
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov  
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen 
 Christian Wennberg    Maarten Wolf      Artem Zhmurov   
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2019, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx editconf, version 2020.2
Executable:   /home/byun/apps/GROMACS/gromacs_cpu-2020.2_gcc-7.5.0_openmpi-4.0.2/bin/gmx_mpi
Data prefix:  /home/byun/apps/GROMACS/gromacs_cpu-2020.2_gcc-7.5.0_openmpi-4.0.2
Working dir:  /home/byun/PROject/CORONAMD/AMBER/CHARMM36-ff/X0072/amber/gmx_MMPBSA
Command line:
  gmx_mpi editconf -f simulation.tpr -o _GMXMMPBSA_LIG.pdb -n _GMXMMPBSA_COM_index.ndx

Reading file simulation.tpr, VERSION 2020.2 (single precision)
Reading file simulation.tpr, VERSION 2020.2 (single precision)

Select a group for output:
Group     0 (         System) has 90160 elements
Group     1 (  GMXMMPBSA_REC) has  4645 elements
Group     2 (      Protein-H) has  2348 elements
Group     3 (        C-alpha) has   304 elements
Group     4 (       Backbone) has   912 elements
Group     5 (      MainChain) has  1217 elements
Group     6 (   MainChain+Cb) has  1495 elements
Group     7 (    MainChain+H) has  1507 elements
Group     8 (      SideChain) has  3138 elements
Group     9 (    SideChain-H) has  1131 elements
Group    10 (    Prot-Masses) has  4645 elements
Group    11 (    non-Protein) has 85515 elements
Group    12 (          Other) has    30 elements
Group    13 (  GMXMMPBSA_LIG) has    26 elements
Group    14 (            POT) has     4 elements
Group    15 (          Water) has 85485 elements
Group    16 (            SOL) has 85485 elements
Group    17 (      non-Water) has  4675 elements
Group    18 (    Protein_LIG) has  4671 elements
Group    19 ( Water_and_ions) has 85489 elements
Group    20 (GMXMMPBSA_REC_GMXMMPBSA_LIG) has  4671 elements
Select a group: 
GROMACS reminds you: "Martin [Karplus] had a green laser, Arieh [Warshel] had a red laser, I have a *blue* laser" (Michael Levitt, Nobel lecture 2013)

Note that major changes are planned in future for editconf, to improve usability and utility.
Read 90160 atoms
Volume: 891.722 nm^3, corresponds to roughly 401200 electrons
No velocities found
Selected 13: 'GMXMMPBSA_LIG'
[INFO   ] Generating AMBER Compatible PDB Files...
[INFO   ] Building Tleap input files...
-I: Adding /opt/AMBER/amber20/dat/leap/prep to search path.
-I: Adding /opt/AMBER/amber20/dat/leap/lib to search path.
-I: Adding /opt/AMBER/amber20/dat/leap/parm to search path.
-I: Adding /opt/AMBER/amber20/dat/leap/cmd to search path.
-f: Source _GMXMMPBSA_leap.in.

Welcome to LEaP!
(no leaprc in search path)
Sourcing: ./_GMXMMPBSA_leap.in
----- Source: /opt/AMBER/amber20/dat/leap/cmd/oldff/leaprc.ff99SB
----- Source of /opt/AMBER/amber20/dat/leap/cmd/oldff/leaprc.ff99SB done
Log file: ./leap.log
Loading parameters: /opt/AMBER/amber20/dat/leap/parm/parm99.dat
Reading title:
PARM99 for DNA,RNA,AA, organic molecules, TIP3P wat. Polariz.& LP incl.02/04/99
Loading parameters: /opt/AMBER/amber20/dat/leap/parm/frcmod.ff99SB
Reading force field modification type file (frcmod)
Reading title:
Modification/update of parm99.dat (Hornak & Simmerling)
Loading library: /opt/AMBER/amber20/dat/leap/lib/all_nucleic94.lib
Loading library: /opt/AMBER/amber20/dat/leap/lib/all_amino94.lib
Loading library: /opt/AMBER/amber20/dat/leap/lib/all_aminoct94.lib
Loading library: /opt/AMBER/amber20/dat/leap/lib/all_aminont94.lib
Loading library: /opt/AMBER/amber20/dat/leap/lib/ions94.lib
Loading library: /opt/AMBER/amber20/dat/leap/lib/solvents.lib
----- Source: /opt/AMBER/amber20/dat/leap/cmd/leaprc.gaff
----- Source of /opt/AMBER/amber20/dat/leap/cmd/leaprc.gaff done
Log file: ./leap.log
Loading parameters: /opt/AMBER/amber20/dat/leap/parm/gaff.dat
Reading title:
AMBER General Force Field for organic molecules (Version 1.81, May 2017)
Loading library: /opt/AMBER/amber20/dat/leap/lib/atomic_ions.lib
Loading parameters: /opt/AMBER/amber20/dat/leap/parm/frcmod.ions234lm_126_tip3p
Reading force field modification type file (frcmod)
Reading title:
Li/Merz ion parameters of divalent to tetravalent ions for TIP3P water model (12-6 normal usage set)
Using H(N)-modified Bondi radii
Loading PDB file: ./_GMXMMPBSA_REC_F1.pdb

/opt/AMBER/amber20/bin/teLeap: Warning!
Unknown residue: HSD   number: 40   type: Nonterminal

/opt/AMBER/amber20/bin/teLeap: Warning!
Unknown residue: HSD   number: 63   type: Nonterminal

/opt/AMBER/amber20/bin/teLeap: Warning!
Unknown residue: HSD   number: 79   type: Nonterminal

/opt/AMBER/amber20/bin/teLeap: Warning!
Unknown residue: HSD   number: 162   type: Nonterminal

/opt/AMBER/amber20/bin/teLeap: Warning!
Unknown residue: HSD   number: 163   type: Nonterminal

/opt/AMBER/amber20/bin/teLeap: Warning!
Unknown residue: HSD   number: 171   type: Nonterminal

/opt/AMBER/amber20/bin/teLeap: Warning!
Unknown residue: HSD   number: 245   type: Nonterminal
Creating new UNIT for residue: HSD sequence: 41

/opt/AMBER/amber20/bin/teLeap: Warning!
One sided connection. Residue () missing connect0 atom.
Created a new atom named: N within residue: .R<HSD 41>
Created a new atom named: CA within residue: .R<HSD 41>
Created a new atom named: CB within residue: .R<HSD 41>
Created a new atom named: ND1 within residue: .R<HSD 41>
Created a new atom named: CG within residue: .R<HSD 41>
Created a new atom named: CE1 within residue: .R<HSD 41>
Created a new atom named: NE2 within residue: .R<HSD 41>
Created a new atom named: CD2 within residue: .R<HSD 41>
Created a new atom named: C within residue: .R<HSD 41>
Created a new atom named: O within residue: .R<HSD 41>

/opt/AMBER/amber20/bin/teLeap: Warning!
One sided connection. Residue (default_name) missing connect1 atom.
Creating new UNIT for residue: HSD sequence: 64

/opt/AMBER/amber20/bin/teLeap: Warning!
One sided connection. Residue () missing connect0 atom.
Created a new atom named: N within residue: .R<HSD 64>
Created a new atom named: CA within residue: .R<HSD 64>
Created a new atom named: CB within residue: .R<HSD 64>
Created a new atom named: ND1 within residue: .R<HSD 64>
Created a new atom named: CG within residue: .R<HSD 64>
Created a new atom named: CE1 within residue: .R<HSD 64>
Created a new atom named: NE2 within residue: .R<HSD 64>
Created a new atom named: CD2 within residue: .R<HSD 64>
Created a new atom named: C within residue: .R<HSD 64>
Created a new atom named: O within residue: .R<HSD 64>

/opt/AMBER/amber20/bin/teLeap: Warning!
One sided connection. Residue (default_name) missing connect1 atom.
Creating new UNIT for residue: HSD sequence: 80

/opt/AMBER/amber20/bin/teLeap: Warning!
One sided connection. Residue () missing connect0 atom.
Created a new atom named: N within residue: .R<HSD 80>
Created a new atom named: CA within residue: .R<HSD 80>
Created a new atom named: CB within residue: .R<HSD 80>
Created a new atom named: ND1 within residue: .R<HSD 80>
Created a new atom named: CG within residue: .R<HSD 80>
Created a new atom named: CE1 within residue: .R<HSD 80>
Created a new atom named: NE2 within residue: .R<HSD 80>
Created a new atom named: CD2 within residue: .R<HSD 80>
Created a new atom named: C within residue: .R<HSD 80>
Created a new atom named: O within residue: .R<HSD 80>

/opt/AMBER/amber20/bin/teLeap: Warning!
One sided connection. Residue (default_name) missing connect1 atom.
Creating new UNIT for residue: HSD sequence: 163

/opt/AMBER/amber20/bin/teLeap: Warning!
One sided connection. Residue () missing connect0 atom.
Created a new atom named: N within residue: .R<HSD 163>
Created a new atom named: CA within residue: .R<HSD 163>
Created a new atom named: CB within residue: .R<HSD 163>
Created a new atom named: ND1 within residue: .R<HSD 163>
Created a new atom named: CG within residue: .R<HSD 163>
Created a new atom named: CE1 within residue: .R<HSD 163>
Created a new atom named: NE2 within residue: .R<HSD 163>
Created a new atom named: CD2 within residue: .R<HSD 163>
Created a new atom named: C within residue: .R<HSD 163>
Created a new atom named: O within residue: .R<HSD 163>
Creating new UNIT for residue: HSD sequence: 164
Created a new atom named: N within residue: .R<HSD 164>
Created a new atom named: CA within residue: .R<HSD 164>
Created a new atom named: CB within residue: .R<HSD 164>
Created a new atom named: ND1 within residue: .R<HSD 164>
Created a new atom named: CG within residue: .R<HSD 164>
Created a new atom named: CE1 within residue: .R<HSD 164>
Created a new atom named: NE2 within residue: .R<HSD 164>
Created a new atom named: CD2 within residue: .R<HSD 164>
Created a new atom named: C within residue: .R<HSD 164>
Created a new atom named: O within residue: .R<HSD 164>

/opt/AMBER/amber20/bin/teLeap: Warning!
One sided connection. Residue (default_name) missing connect1 atom.
Creating new UNIT for residue: HSD sequence: 172

/opt/AMBER/amber20/bin/teLeap: Warning!
One sided connection. Residue () missing connect0 atom.
Created a new atom named: N within residue: .R<HSD 172>
Created a new atom named: CA within residue: .R<HSD 172>
Created a new atom named: CB within residue: .R<HSD 172>
Created a new atom named: ND1 within residue: .R<HSD 172>
Created a new atom named: CG within residue: .R<HSD 172>
Created a new atom named: CE1 within residue: .R<HSD 172>
Created a new atom named: NE2 within residue: .R<HSD 172>
Created a new atom named: CD2 within residue: .R<HSD 172>
Created a new atom named: C within residue: .R<HSD 172>
Created a new atom named: O within residue: .R<HSD 172>

/opt/AMBER/amber20/bin/teLeap: Warning!
One sided connection. Residue (default_name) missing connect1 atom.
Creating new UNIT for residue: HSD sequence: 246

/opt/AMBER/amber20/bin/teLeap: Warning!
One sided connection. Residue () missing connect0 atom.
Created a new atom named: N within residue: .R<HSD 246>
Created a new atom named: CA within residue: .R<HSD 246>
Created a new atom named: CB within residue: .R<HSD 246>
Created a new atom named: ND1 within residue: .R<HSD 246>
Created a new atom named: CG within residue: .R<HSD 246>
Created a new atom named: CE1 within residue: .R<HSD 246>
Created a new atom named: NE2 within residue: .R<HSD 246>
Created a new atom named: CD2 within residue: .R<HSD 246>
Created a new atom named: C within residue: .R<HSD 246>
Created a new atom named: O within residue: .R<HSD 246>

/opt/AMBER/amber20/bin/teLeap: Warning!
One sided connection. Residue (default_name) missing connect1 atom.
Created a new atom named: OT1 within residue: .R<CTHR 304>
Created a new atom named: OT2 within residue: .R<CTHR 304>
  Added missing heavy atom: .R<CTHR 304>.A<O 14>
  Added missing heavy atom: .R<CTHR 304>.A<OXT 15>
  total atoms in file: 2348
  Leap added 2250 missing atoms according to residue templates:
       2 Heavy
       2248 H / lone pairs
  The file contained 72 atoms not in residue templates
Loading PDB file: ./_GMXMMPBSA_LIG_F1.pdb
 (starting new molecule for chain B)

/opt/AMBER/amber20/bin/teLeap: Warning!
Unknown residue: LIG   number: 1   type: Terminal/last
..relaxing end constraints to try for a dbase match

/opt/AMBER/amber20/bin/teLeap: Warning!
  -no luck
Creating new UNIT for residue: LIG sequence: 306
Created a new atom named: C1 within residue: .R<LIG 306>
Created a new atom named: C2 within residue: .R<LIG 306>
Created a new atom named: C3 within residue: .R<LIG 306>
Created a new atom named: C4 within residue: .R<LIG 306>
Created a new atom named: C5 within residue: .R<LIG 306>
Created a new atom named: C6 within residue: .R<LIG 306>
Created a new atom named: C7 within residue: .R<LIG 306>
Created a new atom named: C8 within residue: .R<LIG 306>
Created a new atom named: C9 within residue: .R<LIG 306>
Created a new atom named: N within residue: .R<LIG 306>
Created a new atom named: O1 within residue: .R<LIG 306>
Created a new atom named: O2 within residue: .R<LIG 306>
Created a new atom named: S within residue: .R<LIG 306>
  total atoms in file: 14
  Leap added 2 missing atoms according to residue templates:
       2 H / lone pairs
  The file contained 13 atoms not in residue templates
Checking Unit.
FATAL:  Atom .R<LIG 306>.A<S 13> does not have a type.
FATAL:  Atom .R<LIG 306>.A<O2 12> does not have a type.
FATAL:  Atom .R<LIG 306>.A<O1 11> does not have a type.
FATAL:  Atom .R<LIG 306>.A<N 10> does not have a type.
FATAL:  Atom .R<LIG 306>.A<C9 9> does not have a type.
FATAL:  Atom .R<LIG 306>.A<C8 8> does not have a type.
FATAL:  Atom .R<LIG 306>.A<C7 7> does not have a type.
FATAL:  Atom .R<LIG 306>.A<C6 6> does not have a type.
FATAL:  Atom .R<LIG 306>.A<C5 5> does not have a type.
FATAL:  Atom .R<LIG 306>.A<C4 4> does not have a type.
FATAL:  Atom .R<LIG 306>.A<C3 3> does not have a type.
FATAL:  Atom .R<LIG 306>.A<C2 2> does not have a type.
FATAL:  Atom .R<LIG 306>.A<C1 1> does not have a type.

/opt/AMBER/amber20/bin/teLeap: Fatal Error!
Failed to generate parameters

Exiting LEaP: Errors = 1; Warnings = 21; Notes = 0.
[ERROR  ] /opt/AMBER/amber20/bin/tleap failed when querying _GMXMMPBSA_leap.in
```
