### ISSUE TITLE
[Bug-gmx_MMPBSA]: Loading binary file fails when alanine scanning is performed

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [Valdes-Tresanco-MS/gmx_MMPBSA#258]
### Bug summary

Loading binary file fails when alanine scanning is performed because the residue index list is not computed.

### Terminal output

```bash
Traceback (most recent call last):
  File "/home/mario/programs/miniconda3/envs/gmx_MMPBSA/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/mario/PycharmProjects/gmx_MMPBSA/GMXMMPBSA/analyzer/dialogs.py", line 585, in run_process
    obj = obj_method(**v['args']) if v['args'] else obj_method()
  File "/home/mario/PycharmProjects/gmx_MMPBSA/GMXMMPBSA/API.py", line 246, in load_file
    self._get_fromBinary(self.fname)
  File "/home/mario/PycharmProjects/gmx_MMPBSA/GMXMMPBSA/API.py", line 841, in _get_fromBinary
    self.app_namespace = self._get_namespace(info, 'Binary')
  File "/home/mario/PycharmProjects/gmx_MMPBSA/GMXMMPBSA/API.py", line 874, in _get_namespace
    'mut_str': app.resl[app.mutant_index].mutant_label if app.mutant_index else '',
AttributeError: 'types.SimpleNamespace' object has no attribute 'resl'
```

### gmx_MMPBSA.log

NA

### Python version

1.5.5

**Comment by Valdes-Tresanco-MS** [comment]
via 733bee3e9456fc6c60f8b1448780f732a73f9eeb
