### ISSUE TITLE
[Question]: No module name parmed

### ISSUE THREAD

**Issue by Brandt84** [Valdes-Tresanco-MS/gmx_MMPBSA#277]
### My Question is...

Hi, I installed gmx-MMPBSA and was trying to run the "gmx_MMPBSA_test".  This error showed up:

**Comment by Brandt84** [comment]
ModuleNotFoundError: No module named 'parmed'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brandt/.local/bin/gmx_MMPBSA_test", line 5, in <module>
    from GMXMMPBSA.app import gmxmmpbsa_test
  File "/home/brandt/.local/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 34, in <module>
    raise ImportError('Could not import Amber Python modules. Please make sure '
ImportError: Could not import Amber Python modules. Please make sure you have sourced $AMBERHOME/amber.sh (if you are using sh/ksh/bash/zsh) or $AMBERHOME/amber.csh (if you are using csh/tcsh)

I saw that some people had the same problem and solved it with your help (issue #2 especifically. I could´nt follow, since I am new to this, and  have trouble  with the language and navegating through the commands and terminal.
Could you give me a hand?
Kind regards

**Comment by Valdes-Tresanco-MS** [comment]
It is probably because the `PYTHONPATH` variable does not include this path. Our recommendation is to install gmx_MMPBSA in a conda environment.

**Comment by Valdes-Tresanco-MS** [comment]
Closing due to inactivity. Reopen if necessary

**Comment by Valdes-Tresanco-MS** [comment]
Currently, we put parmed as dependence in the env.yml file for conda installation and the command line for pip installation. I think this problem is already solved. If you have any doubts, please open a new issue
