### ISSUE TITLE
gmx_MMPBSA_test Errors

### ISSUE THREAD

**Issue by wangshuai-simulation** [Valdes-Tresanco-MS/gmx_MMPBSA#316]
I got some errors when i run gmx_MMPBSA_test 
(gmx_MMPBSA v1.5.7 based on MMPBSA version 16.0 and AmberTools 20)
Here are the details:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
COMMAND LINE: gmx_MMPBSA_test -f /home/tea_yiming/wangshuai/test-gmxmmpbsa -t 0 -n 10
[INFO   ] Cloning gmx_MMPBSA repository in /home/tea_yiming/wangshuai/test-gmxmmpbsa/gmx_MMPBSA_test
Cloning into '/home/tea_yiming/wangshuai/test-gmxmmpbsa/gmx_MMPBSA_test'...
remote: Enumerating objects: 19588, done.
remote: Counting objects: 100% (270/270), done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 19588 (delta 111), reused 220 (delta 83), pack-reused 19318
Receiving objects: 100% (19588/19588), 325.47 MiB | 17.25 MiB/s, done.
Resolving deltas: 100% (13784/13784), done.
Checking out files: 100% (678/678), done.
[INFO   ] Cloning gmx_MMPBSA repository...Done.
[INFO   ]                           Example                                STATE
[INFO   ] Protein-Ligand (Single trajectory approximation)               RUNNING
[INFO   ] Protein-Ligand (Single trajectory approximation)       [ 1/16]    DONE
[INFO   ] Protein-Protein                                                RUNNING
[INFO   ] Protein-Protein                                        [ 2/16]    DONE
[INFO   ] Protein-DNA                                                    RUNNING
[INFO   ] Protein-DNA                                            [ 3/16]    DONE
[INFO   ] Protein-Membrane                                               RUNNING
[INFO   ] Protein-Membrane                                       [ 4/16]    DONE
[INFO   ] Protein-Glycan                                                 RUNNING
[INFO   ] Protein-Glycan                                         [ 5/16]    DONE
[INFO   ] Metalloprotein-Peptide                                         RUNNING
[INFO   ] Metalloprotein-Peptide                                 [ 6/16]    DONE
[INFO   ] Comp_receptor                                                  RUNNING
[INFO   ] Comp_receptor                                          [ 7/16]    DONE
[INFO   ] Protein-Ligand (CHARMM force field)                            RUNNING
[INFO   ] Protein-Ligand (CHARMM force field)                    [ 8/16]    DONE
[INFO   ] Protein-ligand complex in membrane with CHARMMff               RUNNING
[INFO   ] Protein-ligand complex in membrane with CHARMMff       [ 9/16]    DONE
[INFO   ] Alanine Scanning                                               RUNNING
[INFO   ] Alanine Scanning                                       [10/16]    DONE
[INFO   ] Stability calculation                                          RUNNING
[INFO   ] Stability calculation                                  [11/16]    DONE
[INFO   ] Decomposition Analysis                                         RUNNING
[INFO   ] Decomposition Analysis                                 [12/16]    DONE
[INFO   ] Interaction Entropy approximation                              RUNNING
**[ERROR  ] Interaction Entropy approximation                      [13/16]   ERROR**
Please, check the test log (/home/tea_yiming/wangshuai/test-gmxmmpbsa/gmx_MMPBSA_test/examples/Entropy_calculations/Interaction_Entropy/15.log)
[INFO   ] Protein-Ligand (Multiple trajectory approximation)             RUNNING
[INFO   ] Protein-Ligand (Multiple trajectory approximation)     [14/16]    DONE
[INFO   ] Entropy calculation using Normal Mode approximation            RUNNING
**[ERROR  ] Entropy calculation using Normal Mode approximation    [15/16]   ERROR**
Please, check the test log (/home/tea_yiming/wangshuai/test-gmxmmpbsa/gmx_MMPBSA_test/examples/Entropy_calculations/nmode/17.log)
[INFO   ] Calculations using 3D-RISM approximation                       RUNNING
**[ERROR  ] Calculations using 3D-RISM approximation               [16/16]   ERROR**
Please, check the test log (/home/tea_yiming/wangshuai/test-gmxmmpbsa/gmx_MMPBSA_test/examples/3D-RISM/18.log)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
So i check the related log files.
For [ERROR Interaction Entropy approximation] 
15.log shows:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
……
[INFO   ] Parsing results to output files...
[INFO   ] Beginning Interaction Entropy calculations...
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 109, in gmxmmpbsa
    app.parse_output_files()
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 1103, in parse_output_files
    self.get_iec2entropy(from_calc)
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 1123, in get_iec2entropy
    ie = InteractionEntropyCalc(edata, self.INPUT)
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/calculation.py", line 676, in __init__
    self._calculate()
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/calculation.py", line 683, in _calculate
    exp_energy_int = np.array([], dtype=np.float)
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'
……
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
About this numpy attribute error, according to a message [from](https://levelup.gitconnected.com/fix-attributeerror-module-numpy-has-no-attribute-float-d7d68c5a4971), do i need to downgrade numpy version (current version is 1.24.0 got from conda list) ?

For [ERROR: Entropy calculation using Normal Mode approximation] 
17.log shows:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
……
[INFO   ] Loading and checking parameter files for compatibility...
[INFO   ] Preparing trajectories for simulation...
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 100, in gmxmmpbsa
    app.file_setup()
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 138, in file_setup
    lig_frames, self.numframes_nmode) = make_trajectories(INPUT, FILES, self.mpi_size,
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_trajs.py", line 228, in make_trajectories
    raise MMPBSA_Error('More processors than complex nmode frames!')
MMPBSA_Error: More processors than complex nmode frames!
……
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
For [ERROR: Calculations using 3D-RISM approximation] 
18.log shows:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
……
[INFO   ] Building AMBER topologies from GROMACS files... Done.
[INFO   ] Loading and checking parameter files for compatibility...
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 100, in gmxmmpbsa
    app.file_setup()
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 127, in file_setup
    create_inputs(INPUT, self.normal_system, self.pre)
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/createinput.py", line 229, in create_inputs
    rism_mdin = SanderRISMInput(INPUT)
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/createinput.py", line 262, in __init__
    self.mdin.change(self.parent_namelist[key], key, INPUT[self.name_map[key]])
  File "/home/tea_yiming/.local/lib/python3.9/site-packages/ParmEd-3.4.3-py3.9-linux-x86_64.egg/parmed/amber/mdin/mdin.py", line 316, in change
    raise InputError('Unknown namelist (%s)!' % namelist)
InputError: Unknown namelist (rism)!
……
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by wangshuai-simulation** [comment]
Thanks a lot if anyone can help me !

**Comment by Valdes-Tresanco-MS** [comment]
Thank you for reporting this problem
Currently, I am in Cuban, so I can't work on the project now.
The first error is definitively related to the NumPy version. I will check
it as soon as possible.
The second error is a bug. It should work fine if you decrease the number
of CPUs. However, I have to fix it as of January 11 when I have access to
my work PC.
The last error is related to the version of parmed. You need to update the
version from my repository as follows:

python -m pip install
***@***.*** -U

If you have difficulties, please check this issue
https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/issues/301

Mario S.

**Comment by wangshuai-simulation** [comment]
Thanks for your reply. I solve all my questions except the error related to the NumPy version. 
Waiting for your further check.
Thanks a lot !

**Comment by Valdes-Tresanco-MS** [comment]
Please try with
conda install numpy<=1.24

Let me know if works for you

**Comment by wangshuai-simulation** [comment]
I solve the problem related to the NumPy version by downgrading NumPy version:
~~~~~~~~~~~~~~~~~~~~~
conda install numpy==1.23.5
~~~~~~~~~~~~~~~~~~~~~
Here are the outputs of gmx_MMPBSA_test
~~~~~~~~~~~~~~~~~~~~~~~~~~
(gmxMMPBSA) [tea_yiming@node04 wangshuai]$ gmx_MMPBSA_test -f /home/tea_yiming/wangshuai/test-gmxmmpbsa -t 0 -n 6
[INFO   ] Cloning gmx_MMPBSA repository in /home/tea_yiming/wangshuai/test-gmxmmpbsa/gmx_MMPBSA_test
Cloning into '/home/tea_yiming/wangshuai/test-gmxmmpbsa/gmx_MMPBSA_test'...
remote: Enumerating objects: 19588, done.
remote: Counting objects: 100% (270/270), done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 19588 (delta 111), reused 220 (delta 83), pack-reused 19318
Receiving objects: 100% (19588/19588), 325.47 MiB | 321.00 KiB/s, done.
Resolving deltas: 100% (13784/13784), done.
Checking out files: 100% (678/678), done.
[INFO   ] Cloning gmx_MMPBSA repository...Done.
[INFO   ]                           Example                                STATE
--------------------------------------------------------------------------------
[INFO   ] Protein-Ligand (Single trajectory approximation)               RUNNING
[INFO   ] Protein-Ligand (Single trajectory approximation)       [ 1/16]    DONE
[INFO   ] Protein-Protein                                                RUNNING
[INFO   ] Protein-Protein                                        [ 2/16]    DONE
[INFO   ] Protein-DNA                                                    RUNNING
[INFO   ] Protein-DNA                                            [ 3/16]    DONE
[INFO   ] Protein-Membrane                                               RUNNING
[INFO   ] Protein-Membrane                                       [ 4/16]    DONE
[INFO   ] Protein-Glycan                                                 RUNNING
[INFO   ] Protein-Glycan                                         [ 5/16]    DONE
[INFO   ] Metalloprotein-Peptide                                         RUNNING
[INFO   ] Metalloprotein-Peptide                                 [ 6/16]    DONE
[INFO   ] Comp_receptor                                                  RUNNING
[INFO   ] Comp_receptor                                          [ 7/16]    DONE
[INFO   ] Protein-Ligand (CHARMM force field)                            RUNNING
[INFO   ] Protein-Ligand (CHARMM force field)                    [ 8/16]    DONE
[INFO   ] Protein-ligand complex in membrane with CHARMMff               RUNNING
[INFO   ] Protein-ligand complex in membrane with CHARMMff       [ 9/16]    DONE
[INFO   ] Alanine Scanning                                               RUNNING
[INFO   ] Alanine Scanning                                       [10/16]    DONE
[INFO   ] Stability calculation                                          RUNNING
[INFO   ] Stability calculation                                  [11/16]    DONE
[INFO   ] Decomposition Analysis                                         RUNNING
[INFO   ] Decomposition Analysis                                 [12/16]    DONE
[INFO   ] Interaction Entropy approximation                              RUNNING
[INFO   ] Interaction Entropy approximation                      [13/16]    DONE
[INFO   ] Protein-Ligand (Multiple trajectory approximation)             RUNNING
[INFO   ] Protein-Ligand (Multiple trajectory approximation)     [14/16]    DONE
[INFO   ] Entropy calculation using Normal Mode approximation            RUNNING
[INFO   ] Entropy calculation using Normal Mode approximation    [15/16]    DONE
[INFO   ] Calculations using 3D-RISM approximation                       RUNNING
[INFO   ] Calculations using 3D-RISM approximation               [16/16]    DONE
--------------------------------------------------------------------------------
[INFO   ] Opening gmx_MMPBSA_ana...
ERROR:root:MMPBSA_Error Could not import PyQt5/PyQt6. gmx_MMPBSA_ana will be disabled until PyQt5/PyQt6 is installed.
Check the gmx_MMPBSA.log file to report the problem.
Traceback (most recent call last):
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA_ana", line 8, in <module>
    sys.exit(gmxmmpbsa_ana())
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 126, in gmxmmpbsa_ana
    GMXMMPBSA_ERROR('Could not import PyQt5/PyQt6. gmx_MMPBSA_ana will be disabled until PyQt5/PyQt6 is '
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 169, in __init__
    raise exc(msg + '\nCheck the gmx_MMPBSA.log file to report the problem.')
GMXMMPBSA.exceptions.MMPBSA_Error: Could not import PyQt5/PyQt6. gmx_MMPBSA_ana will be disabled until PyQt5/PyQt6 is installed
Check the gmx_MMPBSA.log file to report the problem.
~~~~~~~~~~~~~~~~~~~~~~~~~~
The last error doesn't matter to me, as i don't need gmx_MMPBSA_ana.
Anyway, Thanks a lot !

**Comment by Valdes-Tresanco-MS** [comment]
If you are computing in an HPC, this is expected since the HPC has the
graphical driver disabled. If you are computing in a PC, please install
pyqt5 o pyqt6
*python -m pip install pyqt5* or *python -m pip install pyqt6*

We encourage you to use gmx_MMPBSA_ana for your analyses, as it makes
analyzing the results much easier. If you want to add any new analysis or
graph, you can suggest us and we will try to implement it in future
versions.
Mario S.

**Comment by marioernestovaldes** [comment]
Reopened as we need to update the Numpy version in the requirements file...
