### ISSUE TITLE
[Question]: hello,my question is that the sequence number is incorrect for receptor mask and ligand mask in gmx_mmpbsa. How do I choose the right number for receptor mask and ligand mask?

### ISSUE THREAD

**Issue by Luckaswww** [Valdes-Tresanco-MS/gmx_MMPBSA#334]
### My Question is...

[Question]: hello,my question is that the sequence number is incorrect for receptor mask and ligand mask in gmx_mmpbsa. How do I choose the right number for receptor mask and ligand mask? The .xtc and .tpr files were treated by remoing ions and water. is

**Comment by Luckaswww** [comment]
hello,my question is that the sequence number is incorrect for receptor mask and ligand mask in gmx_mmpbsa. How do I choose the right number for receptor mask and ligand mask? The .xtc and .tpr files were treated by remoing ions and water.

**Comment by marioernestovaldes** [comment]
just select the receptor and the ligand groups with the -cg flag and gmx_MMPBSA will generate de receptor and ligand masks accordingly, like in this case for example:

`gmx_MMPBSA -O -i mmpbsa.in -cs com.tpr -ci index.ndx -cg 19 20 -ct com_traj.xtc -o FINAL_RESULTS_MMPBSA.dat`

the index is defined with `-ci index.ndx` and the receptor and ligand groups are previously defined in the index file as groups 19 and 20, respectively. Then. you use `-cg 19 20` to tell gmx_MMPBSA those are the receptor and ligand groups and it will take care of the rest for you

**Comment by Luckaswww** [comment]
Thank you very much for your patient answer. My system has 969 atoms (except water and ions). In the index.ndx file I created, serial number 1 to serial number 810 are the acceptor atoms and 811 to 969 are the ligand atoms. But the matching receptor mask in the .dat file is 1-810 and the ligand mask is 811-820. What I am curious about is that this ligand mask is containing my ligand atoms 811-969? I have this question because I found in an .out file that the ligand mask=811-820 has 159 atoms, which just matches the number of my ligand atoms. But why is it 811-820 instead of 811-969 in the .dat file?

**Comment by Valdes-Tresanco-MS** [comment]
Groups representing the receptor and ligand must appear in the index. For example:
```bash
   0 System              : 65826 atoms
  1 Protein             :  3858 atoms
  2 Protein-H           :  1931 atoms
  3 C-alpha             :   242 atoms
  4 Backbone            :   726 atoms
  5 MainChain           :   970 atoms
  6 MainChain+Cb        :  1197 atoms
  7 MainChain+H         :  1211 atoms
  8 SideChain           :  2647 atoms
  9 SideChain-H         :   961 atoms
 10 Prot-Masses         :  3858 atoms
 11 non-Protein         : 61968 atoms
 12 Water               : 61842 atoms
 13 SOL                 : 61842 atoms
 14 non-Water           :  3984 atoms
 15 Ion                 :   126 atoms
 16 NA                  :    65 atoms
 17 CL                  :    61 atoms
 18 Water_and_ions      : 61968 atoms
 19 receptor            :  2619 atoms
 20 ligand              :  1239 atoms
```
In this case, the receptor is group 19 (containing 2619 atoms) and the ligand is group 20 (containing 1239 atoms). These groups are easily defined. In the case of protein-protein complexes (like this one), they are divided into chains. In the case of a protein-small molecule, the receptor would generally be 1 (Protein in the index) and the ligand 13 (depending on the name of the molecule).
Once you define these groups in gmx_MMPBSA, it takes care of the rest. **You do not need to define any mask.** 
If you are coming from AMBER, please refer to the [GROMACS documentation](https://manual.gromacs.org/current/onlinehelp/gmx-make_ndx.html#gmx-make-ndx) on how the index works.

**Comment by Valdes-Tresanco-MS** [comment]
> Thank you very much for your patient answer. My system has 969 atoms (except water and ions). In the index.ndx file I created, serial number 1 to serial number 810 are the acceptor atoms and 811 to 969 are the ligand atoms. But the matching receptor mask in the .dat file is 1-810 and the ligand mask is 811-820. What I am curious about is that this ligand mask is containing my ligand atoms 811-969? I have this question because I found in an .out file that the ligand mask=811-820 has 159 atoms, which just matches the number of my ligand atoms. But why is it 811-820 instead of 811-969 in the .dat file?

It is difficult to know what you get without the files. Please send us the files (at least the *.tpr and *ndx) to review them and give you more detailed information.

**Comment by Luckaswww** [comment]
[mmpbsa-test.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/10764189/mmpbsa-test.zip)
ok.I upload the file except the .xtc file. Because it so large.

**Comment by Luckaswww** [comment]
I'm so sorry. I have a new problem. The problems occur after the version is updated or reinstalled. I try some solutions but it failed.

BEGIN failed--compilation aborted.
Traceback (most recent call last):
  File "/work/home/nano005/anaconda3/envs/GMX/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 27, in <module>
    from GMXMMPBSA import main
  File "/work/home/nano005/anaconda3/envs/GMX/lib/python3.8/site-packages/GMXMMPBSA/main.py", line 31, in <module>
    from GMXMMPBSA import utils, __version__
  File "/work/home/nano005/anaconda3/envs/GMX/lib/python3.8/site-packages/GMXMMPBSA/utils.py", line 43, in <module>
    import pandas as pd
  File "/work/home/nano005/anaconda3/envs/GMX/lib/python3.8/site-packages/pandas/__init__.py", line 48, in <module>
    from pandas.core.api import (
  File "/work/home/nano005/anaconda3/envs/GMX/lib/python3.8/site-packages/pandas/core/api.py", line 47, in <module>
    from pandas.core.groupby import (
  File "/work/home/nano005/anaconda3/envs/GMX/lib/python3.8/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/work/home/nano005/anaconda3/envs/GMX/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 76, in <module>
    from pandas.core.frame import DataFrame
  File "/work/home/nano005/anaconda3/envs/GMX/lib/python3.8/site-packages/pandas/core/frame.py", line 171, in <module>
    from pandas.core.generic import NDFrame
  File "/work/home/nano005/anaconda3/envs/GMX/lib/python3.8/site-packages/pandas/core/generic.py", line 169, in <module>
    from pandas.core.window import (
  File "/work/home/nano005/anaconda3/envs/GMX/lib/python3.8/site-packages/pandas/core/window/__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (
  File "/work/home/nano005/anaconda3/envs/GMX/lib/python3.8/site-packages/pandas/core/window/ewm.py", line 15, in <module>
    import pandas._libs.window.aggregations as window_aggregations
ImportError: /work/home/nano005/anaconda3/envs/GMX/lib/python3.8/site-packages/numexpr/../../../libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /work/home/nano005/anaconda3/envs/GMX/lib/python3.8/site-packages/pandas/_libs/window/aggregations.cpython-38-x86_64-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/home/nano005/anaconda3/envs/GMX/bin/gmx_MMPBSA", line 5, in <module>
    from GMXMMPBSA.app import gmxmmpbsa
  File "/work/home/nano005/anaconda3/envs/GMX/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 34, in <module>
    raise ImportError('Could not import Amber Python modules. Please make sure '
ImportError: Could not import Amber Python modules. Please make sure you have sourced /work/home/nano005/anaconda3/envs/GMX/amber.sh (if you are using sh/ksh/bash/zsh) or /work/home/nano005/anaconda3/envs/GMX/amber.csh (if you are using csh/tcsh)

**Comment by Valdes-Tresanco-MS** [comment]
What OS are you using? This usually happens on OS like Centos that have older libraries. Here is a possible solution to it (https://groups.google.com/g/gmx_mmpbsa/c/lbbjvewEJi4/m/pYKIotm7CAAJ). In case it doesn't work, try setting `LD_LIBRARY_PATH` (`export LD_LIBRARY_PATH="/path/to/miniconda/envs/gmxMMPBSA/lib"`). 
For some reason, that tpr is not compatible with any of the gromacs versions I have installed. According to the other files, it was created with Gromacs 2022.2, but the latest version (2023) does not read it. Can you check with an additional gromacs version to rule out my problem? 
As I saw, the index.ndx contains duplicate groups, groups with the same name but different number of atoms, etc. I think it is not very consistent. As it can't open the tpr, so I can't generate another new index.

**Comment by Valdes-Tresanco-MS** [comment]
There are many inconsistencies in the generated files. For example: 

![image](https://user-images.githubusercontent.com/36672242/219873155-8cdeb3f8-48ed-447e-bbb3-273ed61615d7.png)

Almost all files have duplicate sections. It's hard to know what's going on, I've never seen anything like this before. I don't know if repeated atoms are being taken, or the notation of the chains and atoms is not correct. As far as I can see, you are using version 1.5.0.3. This version is quite old, consider installing the latest (1.5.7) 
```bash
python -m pip install gmx_MMPBSA -U
```
If possible, send me all the files to run a test and try to identify the problem.
- *.tpr
- *.ndx
- *.top + *.itp + charmm/toppar folder if applicable
- 10 frames *.xtc (you can extract only 10 frames like this: 
```bash
gmx trjconv -f md.xtc -e 100 -o 10_frames_md.xtc
```

**Comment by Luckaswww** [comment]
hello, I updated latest version of gmx_MMPBSA, the same problem is stil exists. And when index.ndx only have receptor, ligand  and receptor-ligand complex ,it is wrong by calcucating gmxMMPBSA. Sorry, I don't understand that you says" there are many inconsistencies in the generatend files”。Could you are a little more specific?  Oh, please forgive me for unfamiliar behavior with the gmx_MMPBSA. I am a novice.
[xtc tpr top.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/10778913/xtc.tpr.top.zip)
[itp.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/10778915/itp.zip)
[charmm36-jul2020.ff.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/10778916/charmm36-jul2020.ff.zip)

**Comment by Luckaswww** [comment]
I have one more question. I wonder if the results is correct. Although the ligand mask is 810 to 820, it contains 159 atoms in _GMXMMPBSA_normal_traj_cpptraj.out file. the 159 atoms just belong to my system.
![image](https://user-images.githubusercontent.com/125569607/219997278-c2e8e544-d996-41b0-9c91-38b1c74b7fec.png)

**Comment by Valdes-Tresanco-MS** [comment]
Don't worry, we will help you.
As I mentioned before, both the index, the topology, and the pdb files that are generated are inconsistent. They have duplicated or discontinuous regions. As you can see in the image, the protein itp has duplicate content and a region of encrypted characters that should not exist. This may be causing the numbering problem.

![image](https://user-images.githubusercontent.com/36672242/219998793-5290721d-8409-4e8b-a645-dee9f6dfeade.png)

Even, after installing the same version of gromacs you used (2022.2) I cannot process your files.

![image](https://user-images.githubusercontent.com/36672242/219998724-8a0a3037-030f-4cf5-8ba4-a375bb76a767.png)

As far as I can see, the executable you used is `gmx_mpi`. I'm not sure, but I think that version is buggy. My recommendation would be to prepare the system using a different version of gromacs than that (2022.2) and completely check all the files before doing the calculations with gmx_MMPBSA. 

I am sure that the problem is not in gmx_MMPBSA since we have tested several systems since the first 1.5.x versions and checked it over and over again. In any case, we do not rule it out and we will be watching to solve all the problems.
Let me know the progress to solve this error

**Comment by Valdes-Tresanco-MS** [comment]
> I have one more question. I wonder if the results is correct. Although the ligand mask is 810 to 820, it contains 159 atoms in _GMXMMPBSA_normal_traj_cpptraj.out file. the 159 atoms just belong to my system. 

`strip [:811-820]` refers to residue selection, not atoms. Please, check the [Amber mask selection syntax](https://amberhub.chpc.utah.edu/atom-mask-selection-syntax/). Note that gmx_MMPBSA does not require this notation

**Comment by Luckaswww** [comment]
First, please accept my sincere appreciation for your help. 

Yes, the gromacs with 2022.2 is used by command gmx_mpi. However, I have other version of gromacs with 2020.4. And I used the gmx_mpi_d command to calculate my job. Subsequently, I use the gmx_MMPBSA with 1.5.7 and check all the files before doing the calculations with gmx_MMPBSA. The problem is same. In my Au111_B6_6_Protein_chain_B.itp file, no see a region of encrypted characters.as you can see in the images.
![image](https://user-images.githubusercontent.com/125569607/220007393-8ab72841-4a42-442b-b0a2-bbadc7c54279.png)

As you mentioned before, the protein itp file or receptor itp must be exist( I am sure that all exist), and strip [:811-820] refers to residue selection, not atoms.
​I might find a reson. Because I defined ten residue number in Protein itp file. In fact, ten residue contains 159 atoms. As you can see in the images.
So receptor mask is 1 to 810, and ligand mask is 811 to 820 that gmx_MMPBSA calculated residue number.
​I am not sure if that's reason. Hope to get your confirmation. if I am right, my calculation data shoule be correct.
![image](https://user-images.githubusercontent.com/125569607/220007524-fd6da026-d5b5-459d-925e-7b686b6bd4b7.png)
![image](https://user-images.githubusercontent.com/125569607/220007640-e951aff8-3ef5-4938-948d-b4748b7aaba5.png)

  


​

**Comment by Valdes-Tresanco-MS** [comment]
> So receptor mask is 1 to 810, and ligand mask is 811 to 820 that gmx_MMPBSA calculated residue number.
> ​I am not sure if that's reason. Hope to get your confirmation. if I am right, my calculation data shoule be correct.

That is correct. We configure gmx_MMPBSA to recognize the residues that are part of the receptor and ligand automatically, even when they are not continuous (for example, receptor 1-100 + 102-200 and ligand 101 or in multimer: receptor 1-100 + 200-300 and ligand 101-199). Amber masks are inclusive, so the groups will always be separated by one residue (in this case receptor 1-810 and ligand 811-820).

I have no idea why your files appear with these problems because I receive multiple files to reproduce errors and only a few of them have these problems. I wish I could reproduce your work to be more sure, but I trust that gmx_MMPBSA is well-tested.

If you have any other questions or require our assistance, please do not hesitate to contact us. When you are ready, close the issue.

**Comment by Luckaswww** [comment]
[edit_top.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/10779740/edit_top.zip)
you can use the script befor use ecitconf.

**Comment by Valdes-Tresanco-MS** [comment]
I don't quite understand what this script does. Unfortunately, I have found no possible way to process your files. I have tried five different versions, and it has not worked with any of them. At least in your case, you were able to run it, so it only remains to analyze the results and check that they are consistent and coherent.
As your initial concern is resolved, I closed the issue. Feel free to reopen it if required or open a new one if it is another issue for better follow-up.
