### ISSUE TITLE
[Bug-gmx_MMPBSA]: PB fail with decomposition

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [Valdes-Tresanco-MS/gmx_MMPBSA#346]
_Reported by **Jennifer Loschwitz** via email_

### Bug summary

When PB is configured with decomposition it fails. This is because the residue section is not included in the mdin. This does not happen in version v1.5.7.

### Terminal output

```bash
[INFO   ] Starting gmx_MMPBSA v1.6.0
[INFO   ] Command-line
  mpirun -np 1 gmx_MMPBSA MPI -O -nogui -i decomp_pb_mmpbsa.in -cs ../md_pbc_fit.pdb -cp Pro_ligand.top -ci ../groups_all.ndx -cg 1 13 -ct ../md_pbc_fit.xtc -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv -do FINAL_DECOMP_MMPBSA.dat -deo FINAL_DECOMP_MMPBSA.csv

[INFO   ] Checking decomp_pb_mmpbsa.in input file...
[INFO   ] Checking decomp_pb_mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /home/.../.../softwares/miniconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /home/.../.../softwares/miniconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /home/.../.../softwares/miniconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /home/.../.../softwares/miniconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /apps/local/qc/gromacs/gromacs-2018/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group Protein_aTP (1_13) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group Protein (1) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group aTP (13) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Checking the structures consistency...
[WARNING] No reference structure was found and the complex structure not contain any chain ID. Assigning chains ID automatically...
[INFO   ] 
[INFO   ] Using topology conversion. Setting radiopt = 0...
[INFO   ] Building Normal Complex Amber topology...
[INFO   ] Detected CHARMM force field topology format...
[INFO   ] Assigning PBRadii charmm_radii to Complex...
[INFO   ] Writing Normal Complex AMBER topology...
[INFO   ] No Receptor topology file was defined. Using ST approach...
[INFO   ] Building AMBER Receptor topology from Complex...
[INFO   ] Assigning PBRadii charmm_radii to Receptor...
[INFO   ] Writing Normal Receptor AMBER topology...
[INFO   ] No Ligand topology file was defined. Using ST approach...
[INFO   ] Building AMBER Ligand topology from Complex...
[INFO   ] Assigning PBRadii charmm_radii to Ligand...
[INFO   ] Writing Normal Ligand AMBER topology...
[INFO   ] Selecting residues by distance (6 Å) between receptor and ligand for decomposition analysis...
[INFO   ] Selected 44 residues:
R::SER:90   R::SER:91   R::TYR:92   R::GLY:93   R::PHE:95   R::GLN:96   R::ASN:97   R::ILE:100  R::PHE:101  R::PHE:110
R::TRP:113  R::ARG:114  R::PHE:117  R::GLN:118  R::PHE:137  R::VAL:138  R::SER:139  R::ASP:140  R::PHE:141  R::ARG:142
R::ALA:144  R::GLN:149  R::LEU:152  R::PHE:155  R::ILE:156  R::ALA:159  R::VAL:160  R::PHE:163  R::PHE:170  R::VAL:171
R::ALA:172  R::LYS:173  R::GLU:174  R::LEU:175  R::PHE:176  R::TYR:183  R::TYR:186  R::TYR:187  R::PHE:190  R::ILE:194
R::SER:201  R::LYS:202  R::MET:203  L::aTP:241

[INFO   ] Cleaning normal complex trajectories...
[INFO   ] Building AMBER topologies from GROMACS files... Done.

[INFO   ] Loading and checking parameter files for compatibility...
[INFO   ] Preparing trajectories for simulation...

[INFO   ] 501 frames were processed by cpptraj for use in calculation.
[INFO   ] Starting calculations in 1 CPUs...

[INFO   ] Running calculations on normal system...
[INFO   ] Beginning PB calculations with /home/.../.../softwares/miniconda3/envs/gmxMMPBSA/bin/sander
[INFO   ]   calculating complex contribution...

              0%|          | 0/501 [elapsed: 00:00 remaining: ?]At line 143 of file /home/conda/feedstock_root/build_artifacts/ambertools_1645002103866/work/AmberTools/src/sander/rgroup.F90 (unit = 5, file = '_GMXMMPBSA_pb_decomp_com.mdin')
Fortran runtime error: End of file

Error termination. Backtrace:
#0  0x14c5153c4068 in read_sf_internal
	at ../../../libgfortran/io/transfer.c:325
#1  0x14c5153c1d7d in read_default_char1
	at ../../../libgfortran/io/read.c:455
#2  0x14c5153c5007 in formatted_transfer_scalar_read
	at ../../../libgfortran/io/transfer.c:1787
#3  0x14c5153c5c66 in formatted_transfer
	at ../../../libgfortran/io/transfer.c:2491
#4  0x55cf6e09a6b8 in ???
#5  0x55cf6e0249fa in ???
#6  0x55cf6dfd081f in ???
#7  0x55cf6dfcdfb6 in ???
#8  0x55cf6dfce02e in ???
#9  0x14c515081082 in __libc_start_main
	at ../csu/libc-start.c:308
#10  0x55cf6de02098 in ???
[ERROR  ] CalcError /home/.../.../softwares/miniconda3/envs/gmxMMPBSA/bin/sander failed with prmtop COM.prmtop!
	
If you are using sander and PB calculation, check the *.mdout files to get the sander error
.
           Check the gmx_MMPBSA.log file to report the problem.
  File "/home/.../.../softwares/miniconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/.../.../softwares/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 101, in gmxmmpbsa
    app.run_mmpbsa()
  File "/home/.../.../softwares/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 205, in run_mmpbsa
    self.calc_list.run(rank, self.stdout)
  File "/home/.../.../softwares/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/calculation.py", line 142, in run
    calc.run(rank, stdout=stdout, stderr=stderr)
  File "/home/.../.../softwares/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/calculation.py", line 625, in run
    GMXMMPBSA_ERROR('%s failed with prmtop %s!\n\t' % (self.program, self.prmtop) +
  File "/home/.../.../softwares/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 169, in __init__
    raise exc(msg + '\nCheck the gmx_MMPBSA.log file to report the problem.')
CalcError: /home/.../.../softwares/miniconda3/envs/gmxMMPBSA/bin/sander failed with prmtop COM.prmtop!
	
If you are using sander and PB calculation, check the *.mdout files to get the sander error

Check the gmx_MMPBSA.log file to report the problem.
Exiting. All files have been retained.
srun: error: node-11: task 0: Exited with exit code 1
```

### gmx_MMPBSA.log

N/A

### gmx_MMPBSA Version

v1.6.0

### Installation

None

**Comment by Valdes-Tresanco-MS** [comment]
Fixed in v1.6.1
