### ISSUE TITLE
[Bug-gmx_MMPBSA]: 

### ISSUE THREAD

**Issue by WoutVanEynde** [Valdes-Tresanco-MS/gmx_MMPBSA#413]
### Bug summary

I want to open older files to recheck some data, however I get the following errors:

I hope you can help me.

Warm regards,
Wout Van Eynde

### Terminal output

```bash
gmx_MMPBSA_ana -f _GMXMMPBSA_info
Traceback (most recent call last):
  File "/home/wout/anaconda3/envs/gmx_MMPBSA/bin/gmx_MMPBSA_ana", line 8, in <module>
    sys.exit(gmxmmpbsa_ana())
  File "/home/wout/anaconda3/envs/gmx_MMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 140, in gmxmmpbsa_ana
    w = GMX_MMPBSA_ANA(ifiles)
  File "/home/wout/anaconda3/envs/gmx_MMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py", line 193, in __init__
    self.gettting_data()
  File "/home/wout/anaconda3/envs/gmx_MMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py", line 947, in gettting_data
    self.init_dialog.get_files_info(self.ifiles)
  File "/home/wout/anaconda3/envs/gmx_MMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/dialogs.py", line 424, in get_files_info
    raise TypeError('The current output files were created with an earlier version of '
TypeError: The current output files were created with an earlier version of gmx_MMPBSA.
Please run "gmx_MMPBSA --rewrite-output" to make them compatible with the current version.

gmx_MMPBSA --rewrite-output
[INFO   ] Starting gmx_MMPBSA v1.6.1
[INFO   ] Command-line
  gmx_MMPBSA --rewrite-output

tets
  File "/home/wout/anaconda3/envs/gmx_MMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/wout/anaconda3/envs/gmx_MMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 105, in gmxmmpbsa
    info.read_info()
  File "/home/wout/anaconda3/envs/gmx_MMPBSA/lib/python3.9/site-packages/GMXMMPBSA/infofile.py", line 189, in read_info
    raise KeyError(f'{e}')
KeyError: "'gbsa'"
Exiting. All files have been retained.
```

### gmx_MMPBSA.log

[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/12589657/gmx_MMPBSA.log)

### Operating system

Linux

### gmx_MMPBSA Version

1.6.1

### Python version

3.9.15

### Installation

None

**Comment by Valdes-Tresanco-MS** [comment]
Create a new _GMMPBSA_info file and remove the line containing the keyword `'gbsa'`. Then, open it as follows:
```bash
gmx_MMPBSA_ana -f new_GMXMMPBSA_info
```
Let me know if this works for you

**Comment by WoutVanEynde** [comment]
This did work for me, thanks a lot!
