### ISSUE TITLE
[Bug-gmx_MMPBSA_test]: 

### ISSUE THREAD

**Issue by alanjchang** [Valdes-Tresanco-MS/gmx_MMPBSA#457]
### Bug summary

I have pip installed the gmx_MMPBSA package, but I keep running into the errors below. I have tried sourcing $AMBERHOME/amber.sh but that file does not seem to exist even after I have run all the steps of installation. I have tried using both the docker file and the installation steps at https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/installation/.

### Terminal output

```bash
gmx_MMPBSA -h
Traceback (most recent call last):
  File "/home/changwg/.local/lib/python3.10/site-packages/GMXMMPBSA/app.py", line 27, in <module>
    from GMXMMPBSA import main
  File "/home/changwg/.local/lib/python3.10/site-packages/GMXMMPBSA/main.py", line 31, in <module>
    from GMXMMPBSA import utils, __version__
  File "/home/changwg/.local/lib/python3.10/site-packages/GMXMMPBSA/utils.py", line 47, in <module>
    import parmed
ModuleNotFoundError: No module named 'parmed'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/changwg/.local/bin/gmx_MMPBSA", line 5, in <module>
    from GMXMMPBSA.app import gmxmmpbsa
  File "/home/changwg/.local/lib/python3.10/site-packages/GMXMMPBSA/app.py", line 34, in <module>
    raise ImportError('Could not import Amber Python modules. Please make sure '
ImportError: Could not import Amber Python modules. Please make sure you have sourced $AMBERHOME/amber.sh (if you are using sh/ksh/bash/zsh) or $AMBERHOME/amber.csh (if you are using csh/tcsh)
```

### Installation

None

**Comment by Valdes-Tresanco-MS** [comment]
You are using the local Python executable, right? Do you have any reason for this? We recommended using the miniconda environment since it contains all necessary dependencies. If you will use the miniconda environment, please, remember to uninstall this instalation

**Comment by alanjchang** [comment]
Just successfully installed the software on a separate server. It seems that something in the installation process went wrong on my original server (perhaps I need to restart it). How do I go about uninstalling the software before I reinstall it? Thank you so much for your help!

**Comment by Valdes-Tresanco-MS** [comment]
You can remove the complete environment and make a fresh install.
```bash
conda deactivate   # only if you activate it
conda env remove -n gmxMMPBSA
```
