### ISSUE TITLE
[Bug-gmx_MMPBSA_ana]: pandas._config.config.OptionError: "No such keys(s): 'mode.use_inf_as_null'"

### ISSUE THREAD

**Issue by camattelaer** [Valdes-Tresanco-MS/gmx_MMPBSA#468]
### Bug summary

when trying to plot the timeseries of dH or -TdS  the program quits unexpectedly with pandas error `pandas._config.config.OptionError: "No such keys(s): 'mode.use_inf_as_null'" `

### Terminal output

```bash
Traceback (most recent call last):
  File "/home/camattelaer/Programs/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/customitem.py", line 371, in fn_btn_group
    self.plotting_line(checked)
  File "/home/camattelaer/Programs/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/customitem.py", line 398, in plotting_line
    self.lp_subw = LineChart(line_plot_data, self.line_chart_action, options=options, item_parent=self)
  File "/home/camattelaer/Programs/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/plots.py", line 215, in __init__
    self.line_plot_ax = sns.lineplot(data=self.data, color=rgb2rgbf(options[('Line Plot', 'line-color')]),
  File "/home/camattelaer/Programs/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/home/camattelaer/Programs/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/seaborn/relational.py", line 710, in lineplot
    p.plot(ax, kwargs)
  File "/home/camattelaer/Programs/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/seaborn/relational.py", line 471, in plot
    for sub_vars, sub_data in self.iter_data(grouping_vars, from_comp_data=True):
  File "/home/camattelaer/Programs/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/seaborn/_core.py", line 983, in iter_data
    data = self.comp_data
  File "/home/camattelaer/Programs/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/seaborn/_core.py", line 1054, in comp_data
    with pd.option_context('mode.use_inf_as_null', True):
  File "/home/camattelaer/Programs/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/pandas/_config/config.py", line 478, in __enter__
    self.undo = [(pat, _get_option(pat)) for pat, val in self.ops]
  File "/home/camattelaer/Programs/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/pandas/_config/config.py", line 478, in <listcomp>
    self.undo = [(pat, _get_option(pat)) for pat, val in self.ops]
  File "/home/camattelaer/Programs/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/pandas/_config/config.py", line 146, in _get_option
    key = _get_single_key(pat, silent)
  File "/home/camattelaer/Programs/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/pandas/_config/config.py", line 132, in _get_single_key
    raise OptionError(f"No such keys(s): {repr(pat)}")
pandas._config.config.OptionError: "No such keys(s): 'mode.use_inf_as_null'"
Aborted (core dumped)
```

### Actual outcome

gmx_MMPBSA_ana crashes and closes

### Expected outcome

gmx_MMPBSA_ana plots the timeseries

### Operating system

ubuntu 22.04

### gmx_MMPBSA_ana Version

gmx_MMPBSA_ana v1.6.2+30.ga8a326d based on MMPBSA version 16.0

### Python version

Python 3.9.15

### Installation

conda AmberTools + pip

**Comment by Valdes-Tresanco-MS** [comment]
Please attach the `conda list` output

**Comment by camattelaer** [comment]
```
# packages in environment at /home/camattelaer/Programs/anaconda3/envs/gmxMMPBSA:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
acpype                    2023.10.27         pyhd8ed1ab_0    conda-forge
ambertools                21.12            py39hc630cb1_0    conda-forge
amberutils                21.0                     pypi_0    pypi
arpack                    3.7.0                hdefa2d7_2    conda-forge
binutils                  2.39                 hdd6e379_1    conda-forge
binutils_impl_linux-64    2.39                 he00db2b_1    conda-forge
binutils_linux-64         2.39                h5fc0e48_13    conda-forge
boost-cpp                 1.74.0               h75c5d50_8    conda-forge
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.24.0               hd590300_0    conda-forge
c-compiler                1.2.0                h7f98852_0    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
cairo                     1.16.0               hb05425b_5  
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
compilers                 1.2.0                ha770c72_0    conda-forge
contourpy                 1.2.0            py39h7633fee_0    conda-forge
curl                      7.87.0               h6312ad2_0    conda-forge
cxx-compiler              1.2.0                h4bd325d_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
cython                    3.0.7            py39h3d6467e_0    conda-forge
expat                     2.5.0                hcb278e6_1    conda-forge
fftw                      3.3.10          nompi_hc118613_108    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonttools                 4.47.0           py39hd1e30aa_0    conda-forge
fortran-compiler          1.2.0                h1990efc_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
gcc_impl_linux-64         9.5.0               h99780fb_19    conda-forge
gcc_linux-64              9.5.0               h4258300_13    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gfortran_impl_linux-64    9.5.0               hf1096a2_19    conda-forge
gfortran_linux-64         9.5.0               hdb51d14_13    conda-forge
git                       2.39.1          pl5321ha3eba64_0    conda-forge
glib                      2.78.1               hfc55251_0    conda-forge
glib-tools                2.78.1               hfc55251_0    conda-forge
gmx-mmpbsa                1.6.2+30.ga8a326d          pypi_0    pypi
gromacs                   2022.4          nompi_hca75aac_100    conda-forge
gxx_impl_linux-64         9.5.0               h99780fb_19    conda-forge
gxx_linux-64              9.5.0               h43f449f_13    conda-forge
hdf4                      4.2.15               h9772cbc_5    conda-forge
hdf5                      1.12.2          nompi_h2386368_101    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
importlib-resources       6.1.1              pyhd8ed1ab_0    conda-forge
importlib_resources       6.1.1              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_16    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5            py39h7633fee_1    conda-forge
krb5                      1.20.1               hf9c8cef_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.39                 hcc3a1bd_1    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libaec                    1.1.2                h59595ed_1    conda-forge
libblas                   3.9.0           20_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           20_linux64_openblas    conda-forge
libclang-cpp14            14.0.6          default_h7634d5b_1    conda-forge
libcurl                   7.87.0               h6312ad2_0    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-devel_linux-64     9.5.0               h0a57e50_19    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgfortran-ng            13.2.0               h69a702a_3    conda-forge
libgfortran5              13.2.0               ha4646dd_3    conda-forge
libglib                   2.78.1               hebfc3b9_0    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libhwloc                  2.9.0                hd6dc26d_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblapack                 3.9.0           20_linux64_openblas    conda-forge
libllvm14                 14.0.6               hcd5def8_4    conda-forge
libnetcdf                 4.8.1           nompi_h261ec11_106    conda-forge
libnghttp2                1.51.0               hdcd2b5c_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.25          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsanitizer              9.5.0               h2f262e1_19    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-devel_linux-64  9.5.0               h0a57e50_19    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libtiff                   4.3.0                h0fcbabc_4    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.2                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.10.3               hca2bb57_4    conda-forge
libzip                    1.9.2                hc869a4a_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
matplotlib-base           3.8.2            py39he9076e7_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpi4py                    3.1.3            py39h32b9844_3    conda-forge
mpich                     4.1.2              h846660c_101    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
netcdf-fortran            4.5.4           nompi_hc402ea5_102    conda-forge
numpy                     1.26.2           py39h474f0d3_0    conda-forge
ocl-icd                   2.3.1                h7f98852_0    conda-forge
olefile                   0.47               pyhd8ed1ab_0    conda-forge
openbabel                 3.1.1            py39h80c93ca_5    conda-forge
openjpeg                  2.5.0                h7d73246_0    conda-forge
openssl                   1.1.1w               hd590300_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
packmol                   20.010               h86c2bf4_0    conda-forge
packmol-memgen            1.2.1rc0                 pypi_0    pypi
pandas                    1.2.2                    pypi_0    pypi
parmed                    3.4.3+11.g41cc9ab          pypi_0    pypi
pcre2                     10.40                hc3806b6_0    conda-forge
perl                      5.32.1          7_hd590300_perl5    conda-forge
pillow                    8.4.0            py39ha612740_0    conda-forge
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
pixman                    0.42.2               h59595ed_0    conda-forge
pocl                      3.1                  h311816e_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pyqt5                     5.15.6                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.13.0                  pypi_0    pypi
pyqt6                     6.6.1                    pypi_0    pypi
pyqt6-qt6                 6.6.2                    pypi_0    pypi
pyqt6-sip                 13.6.0                   pypi_0    pypi
python                    3.9.15          h47a2c10_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      4_cp39    conda-forge
pytraj                    2.0.6                    pypi_0    pypi
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
sander                    16.0                     pypi_0    pypi
scipy                     1.11.4           py39h474f0d3_0    conda-forge
seaborn                   0.11.2                   pypi_0    pypi
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sysroot_linux-64          2.12                he073ed8_16    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tqdm                      4.66.1                   pypi_0    pypi
tzdata                    2023d                h0c530f3_0    conda-forge
unicodedata2              15.1.0           py39hd1e30aa_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.7                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxt                1.3.0                hd590300_1    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

**Comment by derefeq** [comment]
I have been exactly the same
