### ISSUE TITLE
[Bug-gmx_MMPBSA]: PyQt6/QtGui.abi3.so: undefined symbol: _ZN5QFont11tagToStringEj, version Qt_6

### ISSUE THREAD

**Issue by suruchi-25** [Valdes-Tresanco-MS/gmx_MMPBSA#512]
### Bug summary

ImportError: /apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/PyQt6/QtGui.abi3.so: undefined symbol: _ZN5QFont11tagToStringEj, version Qt_6

### Terminal output

```bash
INFO   ] Starting gmx_MMPBSA v1.6.3
[INFO   ] Command-line
  gmx_MMPBSA -i mmpbsa.in -cs md_0_300.tpr -ct md_0_300_center150-300ns.xtc -ci index.ndx -cg 1 13 -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx_mpi found! Using /apps/codes/gromacs-2022/bin/gmx_mpi
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group Protein_6ZV (1_13) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group Protein (1) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group 6ZV (13) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Checking the structures consistency...
[INFO   ] 
[INFO   ] Using topology conversion. Setting radiopt = 0...
[INFO   ] Building Normal Complex Amber topology...
[INFO   ] Detected Amber/OPLS force field topology format...
[WARNING] 24 invalid DIHEDRAL_PERIODICITY = 0 found in Complex topology... Setting DIHEDRAL_PERIODICITY = 1
[INFO   ] Assigning PBRadii mbondi2 to Complex...
[INFO   ] Writing Normal Complex AMBER topology...
[INFO   ] No Receptor topology file was defined. Using ST approach...
[INFO   ] Building AMBER Receptor topology from Complex...
[INFO   ] Assigning PBRadii mbondi2 to Receptor...
[INFO   ] Writing Normal Receptor AMBER topology...
[INFO   ] No Ligand topology file was defined. Using ST approach...
[INFO   ] Building AMBER Ligand topology from Complex...
[INFO   ] Assigning PBRadii mbondi2 to Ligand...
[INFO   ] Writing Normal Ligand AMBER topology...
[INFO   ] Cleaning normal complex trajectories...
[INFO   ] Building AMBER topologies from GROMACS files... Done.

[INFO   ] Loading and checking parameter files for compatibility...
[INFO   ] Preparing trajectories for simulation...

[INFO   ] 2 frames were processed by cpptraj for use in calculation.
[INFO   ] Starting calculations in 1 CPUs...

[INFO   ] Running calculations on normal system...
[INFO   ] Beginning GB calculations with /apps/codes/anaconda3/envs/gmxMMPBSA/bin/sander
[INFO   ]   calculating complex contribution...
            100%|###################################################################################################################################################| 2/2 [elapsed: 00:05 remaining: 00:00]
[INFO   ]   calculating receptor contribution...
            100%|###################################################################################################################################################| 2/2 [elapsed: 00:05 remaining: 00:00]
[INFO   ]   calculating ligand contribution...
            100%|###################################################################################################################################################| 2/2 [elapsed: 00:01 remaining: 00:00]
[INFO   ] Parsing results to output files...

[WARNING] BOND component is reported as inconsistent. Please, check the output file for more details
[INFO   ] Timing:
[INFO   ] Total GROMACS setup time:                   9.292 sec.
[INFO   ] Total AMBER setup time:                     0.823 sec.
[INFO   ] Creating trajectories with cpptraj:         0.127 sec.
[INFO   ] Total calculation time:                    11.354 sec.
[INFO   ] Total GB calculation time:                  7.132 sec.
[INFO   ] Statistics calculation & output writing:    0.018 sec.
[INFO   ] Total time taken:                          21.636 sec.

[INFO   ] 
   Finalizing gmx_MMPBSA: [ERROR  ] = 0; [WARNING] = 2
   Check the gmx_MMPBSA.log file for more details...

[INFO   ] 
 Thank you for using gmx_MMPBSA. Please consider supporting gmx_MMPBSA by citing our publication:
    Valdés-Tresanco, M.S., Valdés-Tresanco, M.E., Valiente, P.A. and Moreno E. 
    gmx_MMPBSA: A New Tool to Perform End-State Free Energy Calculations with GROMACS. 
    J Chem Theory Comput., 2021, 17 (10):6281-6291. Epub 2021 Sep 29. PMID: 34586825.
    https://pubs.acs.org/doi/10.1021/acs.jctc.1c00645

Also consider citing MMPBSA.py:
    Miller III, B. R., McGee Jr., T. D., Swails, J. M. Homeyer, N. Gohlke, H. and Roitberg, A. E.
    MMPBSA.py: An Efficient Program for End-State Free Energy Calculations.
    J. Chem. Theory Comput., 2012, 8 (9) pp 3314-3321

[INFO   ] Opening gmx_MMPBSA_ana to analyze results...

Traceback (most recent call last):
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA_ana", line 8, in <module>
    sys.exit(gmxmmpbsa_ana())
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/app.py", line 129, in gmxmmpbsa_ana
    from GMXMMPBSA.analyzer.gui import GMX_MMPBSA_ANA
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/analyzer/gui.py", line 32, in <module>
    from GMXMMPBSA.analyzer.plots import Tables
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/analyzer/plots.py", line 38, in <module>
    from matplotlib.backends import qt_compat
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/matplotlib/backends/qt_compat.py", line 120, in <module>
    _setup_pyqt5plus()
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/matplotlib/backends/qt_compat.py", line 91, in _setup_pyqt5plus
    from PyQt6 import QtCore, QtGui, QtWidgets, sip
ImportError: /apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/PyQt6/QtGui.abi3.so: undefined symbol: _ZN5QFont11tagToStringEj, version Qt_6
[ERROR  ] Unable to start gmx_MMPBSA_ana...
[INFO   ] Finalized...
```

### gmx_MMPBSA.log

[gmx_MMPBSA.log](https://github.com/user-attachments/files/15747033/gmx_MMPBSA.log)

### Operating system

ubuntu

### gmx_MMPBSA Version

gmx_MMPBSA v1.6.3

### Python version

Python 3.10.14

### Installation

None

**Comment by fgrcampos** [comment]
Why was this issue closed? Was any solution found for this error? If so, what must be done to solve it?
