### ISSUE TITLE
[Bug-gmx_MMPBSA_ana]:KeyError : "delta"

### ISSUE THREAD

**Issue by Arikite-netizen** [Valdes-Tresanco-MS/gmx_MMPBSA#516]
### Bug summary

gmx_MMPBSA_ana crashes just after loading the data for analysis. I have tried multiple times, but each time the same error  occurs for the same system. However, this error doesn't occur for any other system. Could you please help me understand why is this system not been read by the gmx_MMPBSA_ana package

### Terminal output

```bash
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/nfb/miniconda3/envs/gmxMMPBSA/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/nfb/miniconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/analyzer/dialogs.py", line 605, in run_process
    obj = obj_method(**v['args']) if v['args'] else obj_method()
  File "/home/nfb/miniconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/API.py", line 850, in get_ana_data
    dict(data=decomp[level][level1][level2][level3], level=item_lvl,
  File "/home/nfb/miniconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/nfb/miniconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'delta'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nfb/miniconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/analyzer/dialogs.py", line 618, in run
    for result in imap_unordered_it:
  File "/home/nfb/miniconda3/envs/gmxMMPBSA/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
KeyError: 'delta'
Aborted (core dumped)
```

### Actual outcome

Gmx_MMPBSA_ana crashes immediately after reading the files by clicking on the Accept button

### Expected outcome

To be able to open the analysis and navigate through the plots from the trajectories

### Additional information

Methods such as gb and decomp were used. One noticeable condition I noticed is a exceptionally low binding energy about -0.37 kcal/mol.

### Operating system

Ubuntu 22 LTS

### gmx_MMPBSA_ana Version

gmx_MMPBSA_ana v1.6.3

### Python version

3.10

### Installation

AmberTools compilation + conda

**Comment by meowstudy** [comment]
Same problem, have you solved the problem?

**Comment by gongshuai0606** [comment]
> ### Bug summary
> gmx_MMPBSA_ana crashes just after loading the data for analysis. I have tried multiple times, but each time the same error occurs for the same system. However, this error doesn't occur for any other system. Could you please help me understand why is this system not been read by the gmx_MMPBSA_ana package
> 
> ### Terminal output
> ```shell
> multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/home/nfb/miniconda3/envs/gmxMMPBSA/lib/python3.10/multiprocessing/pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>   File "/home/nfb/miniconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/analyzer/dialogs.py", line 605, in run_process
>     obj = obj_method(**v['args']) if v['args'] else obj_method()
>   File "/home/nfb/miniconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/API.py", line 850, in get_ana_data
>     dict(data=decomp[level][level1][level2][level3], level=item_lvl,
>   File "/home/nfb/miniconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/pandas/core/frame.py", line 4102, in __getitem__
>     indexer = self.columns.get_loc(key)
>   File "/home/nfb/miniconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 417, in get_loc
>     raise KeyError(key)
> KeyError: 'delta'
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/nfb/miniconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/analyzer/dialogs.py", line 618, in run
>     for result in imap_unordered_it:
>   File "/home/nfb/miniconda3/envs/gmxMMPBSA/lib/python3.10/multiprocessing/pool.py", line 873, in next
>     raise value
> KeyError: 'delta'
> Aborted (core dumped)
> ```
> 
> ### Actual outcome
> Gmx_MMPBSA_ana crashes immediately after reading the files by clicking on the Accept button
> 
> ### Expected outcome
> To be able to open the analysis and navigate through the plots from the trajectories
> 
> ### Additional information
> Methods such as gb and decomp were used. One noticeable condition I noticed is a exceptionally low binding energy about -0.37 kcal/mol.
> 
> ### Operating system
> Ubuntu 22 LTS
> 
> ### gmx_MMPBSA_ana Version
> gmx_MMPBSA_ana v1.6.3
> 
> ### Python version
> 3.10
> 
> ### Installation
> AmberTools compilation + conda

Same problem, have you solved the problem?

**Comment by Valdes-Tresanco-MS** [comment]
Please, attach the file to check what is happening
