### ISSUE TITLE
[Question]: I am not able to install gmxmmpbsa on ubuntu 2024. 

### ISSUE THREAD

**Issue by AKR845** [Valdes-Tresanco-MS/gmx_MMPBSA#517]
### My Question is...

/tmp/pip-build-env-8i30r4s1/overlay/lib/python3.10/site-packages/numpy/_core/include/numpy/ndarrayobject.h:139:62: note: in definition of macro ‘PyArray_GETPTR1’         139 |                                          (i)*PyArray_STRIDES(obj)[0]))             |                                                              ^~~       /tmp/pip-build-env-8i30r4s1/overlay/lib/python3.10/site-packages/numpy/_core/include/numpy/ndarraytypes.h:1526:38: note: expected ‘const PyArrayObject *’ {aka ‘const struct tagPyArrayObject_fields *’} but argument is of type ‘PyObject *’ {aka ‘struct _object *’}        1526 | PyArray_STRIDES(const PyArrayObject *arr)             |                 ~~~~~~~~~~~~~~~~~~~~~^~~       pandas/_libs/src/ujson/python/JSONtoObj.c:319:31: warning: passing argument 1 of ‘PyArray_SETITEM’ from incompatible pointer type [-Wincompatible-pointer-types]         319 |         PyArray_SETITEM(npyarr->ret, item, value) == -1) {             |                         ~~~~~~^~~~~             |                               |             |                               PyObject * {aka struct _object *}       /tmp/pip-build-env-8i30r4s1/overlay/lib/python3.10/site-packages/numpy/_core/include/numpy/ndarrayobject.h:292:32: note: expected ‘PyArrayObject *’ {aka ‘struct tagPyArrayObject_fields *’} but argument is of type ‘PyObject *’ {aka ‘struct _object *’}         292 | PyArray_SETITEM(PyArrayObject *arr, char *itemptr, PyObject *v)             |                 ~~~~~~~~~~~~~~~^~~       error: command '/usr/bin/gcc' failed with exit code 1       [end of output]      note: This error originates from a subprocess, and is likely not a problem with pip.   ERROR: Failed building wheel for pandas Failed to build pandas

**Comment by AKR845** [comment]
![Screenshot from 2024-07-04 19-29-03](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/174723957/a4c99598-f2b1-41b8-b523-96244548e968)
![Screenshot from 2024-07-04 18-54-14](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/174723957/195b0cb1-6499-49d8-b299-0ac6dda6164c)
Please help me to solve this

**Comment by Valdes-Tresanco-MS** [comment]
What version of pandas are you trying to install?

**Comment by Valdes-Tresanco-MS** [comment]
Probably this pandas version ends in an error. Please, try to install the 1.2.2

**Comment by Valdes-Tresanco-MS** [comment]
@denizkavi, @AKR845  I don't know why this is happening, but this configuration works for me

```bash
conda create -n gmxMMPBSA python=3.9 -y -q
conda activate gmxMMPBSA
```
```bash
conda install -c conda-forge "mpi4py<=3.1.5" "ambertools<=23.3" -y -q
```
```bash
python -m pip install "numpy==1.22.3" "pandas==1.2.2" "pyqt6<=6.6.1"
```

Please, let me know if this works for you

**Comment by vaghasiyautsav** [comment]
No this is not working. Still getting same error. 

`pandas/_libs/src/ujson/python/JSONtoObj.c:319:31: warning: passing argument 1 of ‘PyArray_SETITEM’ from incompatible pointer type [-Wincompatible-pointer-types]
        319 |         PyArray_SETITEM(npyarr->ret, item, value) == -1) {
            |                         ~~~~~~^~~~~
            |                               |
            |                               PyObject * {aka struct _object *}
      /tmp/pip-build-env-r9ohf93i/overlay/lib/python3.10/site-packages/numpy/_core/include/numpy/ndarrayobject.h:292:32: note: expected ‘PyArrayObject *’ {aka ‘struct tagPyArrayObject_fields *’} but argument is of type ‘PyObject *’ {aka ‘struct _object *’}
        292 | PyArray_SETITEM(PyArrayObject *arr, char *itemptr, PyObject *v)
            |                 ~~~~~~~~~~~~~~~^~~
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pandas
Failed to build pandas
ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects
`

**Comment by Jameel9** [comment]
Hi all,

I installed gmx_MMPBSA on my laptop (Ubuntu) a month ago using the method of conda and the .yml file. It was smooth and successful. Yesterday, I tried to install the tool on my PC at work and I got the exact error reported in this issue. I tried the newly suggested method ([above](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/issues/517#issuecomment-2211174282)) and it didn't work. 
It's very likely that the issue is caused by a third-party library/software that got updated recently.

**Comment by Valdes-Tresanco-MS** [comment]
Please, try to create a conda environment using Python 3.9 as the base.

**Comment by Jameel9** [comment]
> Please, try to create a conda environment using Python 3.9 as the base.

I did but still get this:

(gmxMMPBSA) jameel@users-Precision-3460:~$ python -m pip install "numpy==1.22.3" "pandas==1.2.2" "pyqt6<=6.6.1"
Collecting numpy==1.22.3
  Using cached numpy-1.22.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.0 kB)
Collecting pandas==1.2.2
  Using cached pandas-1.2.2-cp39-cp39-manylinux1_x86_64.whl.metadata (4.7 kB)
Collecting pyqt6<=6.6.1
  Using cached PyQt6-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl.metadata (2.1 kB)
Requirement already satisfied: python-dateutil>=2.7.3 in ./miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages (from pandas==1.2.2) (2.9.0)
Requirement already satisfied: pytz>=2017.3 in ./miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages (from pandas==1.2.2) (2024.1)
Collecting PyQt6-sip<14,>=13.6 (from pyqt6<=6.6.1)
  Using cached PyQt6_sip-13.8.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl.metadata (420 bytes)
Collecting PyQt6-Qt6>=6.6.0 (from pyqt6<=6.6.1)
  Using cached PyQt6_Qt6-6.7.2-py3-none-manylinux_2_28_x86_64.whl.metadata (534 bytes)
Requirement already satisfied: six>=1.5 in ./miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas==1.2.2) (1.16.0)
Using cached numpy-1.22.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Using cached pandas-1.2.2-cp39-cp39-manylinux1_x86_64.whl (9.7 MB)
Using cached PyQt6-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl (7.9 MB)
Using cached PyQt6_Qt6-6.7.2-py3-none-manylinux_2_28_x86_64.whl (74.3 MB)
Using cached PyQt6_sip-13.8.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (281 kB)
Installing collected packages: PyQt6-Qt6, PyQt6-sip, numpy, pyqt6, pandas
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
matplotlib 3.9.1 requires numpy>=1.23, but you have numpy 1.22.3 which is incompatible.
scipy 1.13.1 requires numpy<2.3,>=1.22.4, but you have numpy 1.22.3 which is incompatible.
Successfully installed PyQt6-Qt6-6.7.2 PyQt6-sip-13.8.0 numpy-1.22.3 pandas-1.2.2 pyqt6-6.6.1

**Comment by fgrcampos** [comment]
> @denizkavi, @AKR845 I don't know why this is happening, but this configuration works for me
> 
> ```shell
> conda create -n gmxMMPBSA python=3.9 -y -q
> conda activate gmxMMPBSA
> ```
> 
> ```shell
> conda install -c conda-forge "mpi4py<=3.1.5" "ambertools<=23.3" -y -q
> ```
> 
> ```shell
> python -m pip install "numpy==1.22.3" "pandas==1.2.2" "pyqt6<=6.6.1"
> ```
> 
> Please, let me know if this works for you

This solution has worked for me, with the exception of the numpy version being 1.23 for compatibility with other packages.

**Comment by Jameel9** [comment]
Hi @Valdes-Tresanco-MS,
 
Hi @fgrcampos, I did follow the steps and 
`python -m pip install gmx_MMPBSA`
but when I ran 
`gmx_MMPBSA -h`
I got this error

(gmxMMPBSA) shirehorse@shirehorse-Precision-3460:~/Downloads$ gmx_MMPBSA
Traceback (most recent call last):
  File "/home/shirehorse/miniconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 5, in <module>
    from GMXMMPBSA.app import gmxmmpbsa
  File "/home/shirehorse/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 27, in <module>
    from GMXMMPBSA import main
  File "/home/shirehorse/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 31, in <module>
    from GMXMMPBSA import utils, __version__
  File "/home/shirehorse/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/utils.py", line 43, in <module>
    import pandas as pd
  File "/home/shirehorse/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/pandas/__init__.py", line 29, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "/home/shirehorse/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by Jameel9** [comment]
Hi everyone, 

I just used the following commands, and I finally got an old version 1.5.0.3 (Feb. 2022). But it is working. I have just done MMGBSA calculations for a complex. 

```
conda create -n gmxMMPBSA 
conda activate gmxMMPBSA
conda install -c conda-forge mpi4py ambertools -y -q
pip install PyQt6 
conda install conda-forge::gmx_mmpbsa
```
Even though the last command is supposed to install the 1.6.3 version (as the conda page claims), but it doesn't actually.

Don't try to update the tool via 
`pip install gmx-MMPBSA --upgrade `

because you will end up with the error of which this issue was created.

**Comment by hanahg** [comment]
I used the method you proposed, but yet I have problem. after following command, 
conda create -n gmxMMPBSA 
conda activate gmxMMPBSA
conda install -c conda-forge mpi4py ambertools -y -q
pip install PyQt5 
conda install conda-forge::gmx_mmpbsa

the gmx_mmpbsa: gmx_mmpbsa: command not found

**Comment by Jameel9** [comment]
Last week I followed the installation process provided by the developers abd it was installed properly without any problems.

**Comment by hanahg** [comment]
The problem is resolved.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
