### ISSUE TITLE
[Bug-gmx_MMPBSA_ana]: Could not import PyQt5/PyQt6

### ISSUE THREAD

**Issue by mglgc** [Valdes-Tresanco-MS/gmx_MMPBSA#533]
### Bug summary

Under a gmxMMPBSA conda env with a successfull gmx_MMPBSA_test running, gmx_MMPBSA_ana execution renders the error.

### Terminal output

```bash
ERROR:root:MMPBSA_Error 

Could not import PyQt5/PyQt6. gmx_MMPBSA_ana will be disabled until PyQt5/PyQt6 is installed

Check the gmx_MMPBSA.log file to report the problem.
Traceback (most recent call last):
  File "/home/csic/sdb/mgl/.local/bin/gmx_MMPBSA_ana", line 8, in <module>
    sys.exit(gmxmmpbsa_ana())
  File "/home/csic/sdb/mgl/.local/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 126, in gmxmmpbsa_ana
    GMXMMPBSA_ERROR('Could not import PyQt5/PyQt6. gmx_MMPBSA_ana will be disabled until PyQt5/PyQt6 is '
  File "/home/csic/sdb/mgl/.local/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 171, in __init__
    raise exc('\n\n' + msg + '\n\nCheck the gmx_MMPBSA.log file to report the problem.')
GMXMMPBSA.exceptions.MMPBSA_Error: 

Could not import PyQt5/PyQt6. gmx_MMPBSA_ana will be disabled until PyQt5/PyQt6 is installed

Check the gmx_MMPBSA.log file to report the problem.
```

### Actual outcome

ERROR:root:MMPBSA_Error 

Could not import PyQt5/PyQt6. gmx_MMPBSA_ana will be disabled until PyQt5/PyQt6 is installed

Check the gmx_MMPBSA.log file to report the problem.
Traceback (most recent call last):
  File "/home/csic/sdb/mgl/.local/bin/gmx_MMPBSA_ana", line 8, in <module>
    sys.exit(gmxmmpbsa_ana())
  File "/home/csic/sdb/mgl/.local/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 126, in gmxmmpbsa_ana
    GMXMMPBSA_ERROR('Could not import PyQt5/PyQt6. gmx_MMPBSA_ana will be disabled until PyQt5/PyQt6 is '
  File "/home/csic/sdb/mgl/.local/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 171, in __init__
    raise exc('\n\n' + msg + '\n\nCheck the gmx_MMPBSA.log file to report the problem.')
GMXMMPBSA.exceptions.MMPBSA_Error: 

Could not import PyQt5/PyQt6. gmx_MMPBSA_ana will be disabled until PyQt5/PyQt6 is installed

Check the gmx_MMPBSA.log file to report the problem.

### Expected outcome

A normal gmx_MMPBSA_ana running gui interface.

### Additional information

conda list | grep pyqt
pyqt6                     6.6.1
pyqt6-qt6                 6.7.2
pyqt6-sip                 13.8.0

### Operating system

Rocky Linux release 8.4

### Python version

Python 3.9.19

### Installation

pip

**Comment by Valdes-Tresanco-MS** [comment]
Please, try to reinstall pyqt

**Comment by mglgc** [comment]
Dear Mario,
Thank you for your reply. I've just uninstall/install pyqt (python -m pip {uninstall,install} pyqt6) but the issue remains with the same output error lines as before. Additional help for fixing will be welcome. Thanks in advance.

**Comment by Valdes-Tresanco-MS** [comment]
Sorry for the delay.  gmx_MMPBSA is installed in your local Python package path. Please, use a conda environment following the instructions in our documentation. Make sure that the Python interpreter is the one in the conda environment and that you don't have defined the PYTHONPATH variable

**Comment by chenDeepin** [comment]
If you're working in a conda env, try this:
export QT_QPA_PLATFORM=offscreen
