### ISSUE TITLE
[Bug-gmx_MMPBSA_ana]: Analysis with QH runs prevent GUI analysis 

### ISSUE THREAD

**Issue by bdratch** [Valdes-Tresanco-MS/gmx_MMPBSA#535]
### Bug summary

Hello,
I am trying to analyze the results of a gmx_MMPBSA run using gmx_MMPBA_ana, however, when the files are read the program crashes. It is important to note this is only an issue when qh_entropy = 1 in my pb_input.in file but I am interested in calculating entropy.   

### Terminal output

```bash
(gmxMMPBSA) kate@Wrekin mdfit1 % gmx_MMPBSA_ana
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/kate/miniconda3/envs/gmxMMPBSA/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/kate/miniconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/analyzer/dialogs.py", line 605, in run_process
    obj = obj_method(**v['args']) if v['args'] else obj_method()
  File "/Users/kate/miniconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/API.py", line 772, in get_ana_data
    entropy_map, entropy, entropy_summary = self.get_entropy(**entropy_options, verbose=verbose).values()
  File "/Users/kate/miniconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/API.py", line 542, in get_entropy
    _m, _d, _s = self.get_qh_entropy(etype, mol, term).values()
  File "/Users/kate/miniconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/API.py", line 440, in get_qh_entropy
    df = pd.DataFrame(flatten(entropy))
  File "/Users/kate/miniconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/pandas/core/frame.py", line 529, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/Users/kate/miniconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 287, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/Users/kate/miniconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 80, in arrays_to_mgr
    index = extract_index(arrays)
  File "/Users/kate/miniconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 391, in extract_index
    raise ValueError("If using all scalar values, you must pass an index")
ValueError: If using all scalar values, you must pass an index
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kate/miniconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/analyzer/dialogs.py", line 618, in run
    for result in imap_unordered_it:
  File "/Users/kate/miniconda3/envs/gmxMMPBSA/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
ValueError: If using all scalar values, you must pass an index
zsh: abort      gmx_MMPBSA_ana
(gmxMMPBSA) kate@Wrekin mdfit1 % /Users/kate/miniconda3/envs/gmxMMPBSA/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

### Actual outcome

The gmx_MMPBSA_ana windows quits and a Mac error reading "python3.10 quit unexpectedly"

### Expected outcome

My expected outcome is the analysis program will load the gmx_MMPBSA data and I'd be able to view how the energetic values changed throughout the simulation time.

### Additional information

I've copied the 'python3.10 quit unexpectedly' details incase this helps.
[python3.10 quit unexpectedly.txt](https://github.com/user-attachments/files/17032795/python3.10.quit.unexpectedly.txt)

### Operating system

macOS Ventura 13.4.1

### gmx_MMPBSA_ana Version

gmx_MMPBSA_ana v1.6.3 based on MMPBSA version 16.0

### Python version

Python 3.10.9

### Installation

pip

**Comment by Valdes-Tresanco-MS** [comment]
Unfortunately, since it has issues and is quite inefficient, we will probably remove it in future releases.
