### ISSUE TITLE
[Bug-gmx_MMPBSA_ana]: 

### ISSUE THREAD

**Issue by Jackshoulder** [Valdes-Tresanco-MS/gmx_MMPBSA#548]
### Bug summary

gmx_MMPBSA_ana

### Terminal output

```bash
gmx_MMPBSA_ana
Traceback (most recent call last):
  File "/root/anaconda3/envs/gmxMMPBSA/lib/python3.11/site-packages/GMXMMPBSA/analyzer/customitem.py", line 373, in fn_btn_group
    self.plotting_bar(checked)
  File "/root/anaconda3/envs/gmxMMPBSA/lib/python3.11/site-packages/GMXMMPBSA/analyzer/customitem.py", line 423, in plotting_bar
    self.bp_subw = BarChart(bar_plot_data, self.bar_chart_action, options=options, item_parent=self)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/gmxMMPBSA/lib/python3.11/site-packages/GMXMMPBSA/analyzer/plots.py", line 289, in __init__
    bl = bar_label(bar_plot_ax, bar_plot_ax.containers[1],
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/gmxMMPBSA/lib/python3.11/site-packages/GMXMMPBSA/analyzer/utils.py", line 144, in bar_label
    endpt = err[:, 1].max() if dat >= 0 else err[:, 1].min()
                                             ~~~^^^^^^
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

### Actual outcome

![截图 2024-11-20 14-00-05](https://github.com/user-attachments/assets/7a207e49-7fd7-4e00-9da5-606889803fed)

### Expected outcome

with a results

### Operating system

ubuntu

### gmx_MMPBSA_ana Version

gmx_MMPBSA_ana 1.6.4 based on MMPBSA version 16.0

### Python version

Python 3.11.8

### Installation

pip

**Comment by marioernestovaldes** [comment]
fixed in 1e8bdeddc741373cce61d1be153a6ab6d2033399
