### ISSUE TITLE
[Bug-gmx_MMPBSA_ana]: 

### ISSUE THREAD

**Issue by pankaj209h** [Valdes-Tresanco-MS/gmx_MMPBSA#552]
### Bug summary

Hi I am getting this error. Please help me to solve this issue. 

Thank you so much.

### Terminal output

```bash
(AmberTools23) bhattpan@dev-amd20-v100:/mnt/gs21/scratch/bhattpan/2p$ mpirun -np 2 gmx_MMPBSA -O -i mmpbsa.in -cs md_0_100.tpr -              ci index.ndx -cg 1 13 -ct md_0_100_center.xtc -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv
[INFO   ] Starting gmx_MMPBSA v1.5.7+96.g30d3e442
[INFO   ] Command-line
  mpirun -np 2 gmx_MMPBSA -O -i mmpbsa.in -cs md_0_100.tpr -ci index.ndx -cg 1 13 -ct md_0_100_center.xtc -cp topol.top -o FINAL              _RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /mnt/home/bhattpan/anaconda3/envs/AmberTools23/bin/cpptraj
[INFO   ] tleap found! Using /mnt/home/bhattpan/anaconda3/envs/AmberTools23/bin/tleap
[INFO   ] parmchk2 found! Using /mnt/home/bhattpan/anaconda3/envs/AmberTools23/bin/parmchk2
[INFO   ] sander found! Using /mnt/home/bhattpan/anaconda3/envs/AmberTools23/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /opt/software-current/2023.06/x86_64/intel/skylake_avx512/software/GROMACS/2024.1-foss-2023b/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group Protein_LIG (1_13) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group Protein (1) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group LIG (13) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Checking the structures consistency...
[INFO   ]
[INFO   ] Using topology conversion. Setting radiopt = 0...
[INFO   ] Building Normal Complex Amber topology...
[INFO   ] Detected CHARMM force field topology format...
[INFO   ] Assigning PBRadii mbondi2 to Complex...
[INFO   ] Writing Normal Complex AMBER topology...
[INFO   ] No Receptor topology file was defined. Using ST approach...
[INFO   ] Building AMBER Receptor topology from Complex...
[INFO   ] Assigning PBRadii mbondi2 to Receptor...
[INFO   ] Writing Normal Receptor AMBER topology...
[INFO   ] No Ligand topology file was defined. Using ST approach...
[INFO   ] Building AMBER Ligand topology from Complex...
[INFO   ] Assigning PBRadii mbondi2 to Ligand...
[INFO   ] Writing Normal Ligand AMBER topology...
[INFO   ] Cleaning normal complex trajectories...
[INFO   ] Building AMBER topologies from GROMACS files... Done.

[INFO   ] Loading and checking parameter files for compatibility...
[INFO   ] Preparing trajectories for simulation...

^C(AmberTools23) bhattpan@dev-amd20-v100:/mnt/gs21/scratch/bhattpan/2pmpirun -np 40 gmx_MMPBSA -O -i mmpbsa.in -cs md_0_100.tpr               -ci index.ndx -cg 1 13 -ct md_0_100_fit.xtc -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv
[INFO   ] Starting gmx_MMPBSA v1.5.7+96.g30d3e442
[INFO   ] Command-line
  mpirun -np 40 gmx_MMPBSA -O -i mmpbsa.in -cs md_0_100.tpr -ci index.ndx -cg 1 13 -ct md_0_100_fit.xtc -cp topol.top -o FINAL_R              ESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /mnt/home/bhattpan/anaconda3/envs/AmberTools23/bin/cpptraj
[INFO   ] tleap found! Using /mnt/home/bhattpan/anaconda3/envs/AmberTools23/bin/tleap
[INFO   ] parmchk2 found! Using /mnt/home/bhattpan/anaconda3/envs/AmberTools23/bin/parmchk2
[INFO   ] sander found! Using /mnt/home/bhattpan/anaconda3/envs/AmberTools23/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /opt/software-current/2023.06/x86_64/intel/skylake_avx512/software/GROMACS/2024.1-foss-2023b/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group Protein_LIG (1_13) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group Protein (1) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group LIG (13) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Checking the structures consistency...
[INFO   ]
[INFO   ] Using topology conversion. Setting radiopt = 0...
[INFO   ] Building Normal Complex Amber topology...
[INFO   ] Detected CHARMM force field topology format...
[INFO   ] Assigning PBRadii mbondi2 to Complex...
[INFO   ] Writing Normal Complex AMBER topology...
[INFO   ] No Receptor topology file was defined. Using ST approach...
[INFO   ] Building AMBER Receptor topology from Complex...
[INFO   ] Assigning PBRadii mbondi2 to Receptor...
[INFO   ] Writing Normal Receptor AMBER topology...
[INFO   ] No Ligand topology file was defined. Using ST approach...
[INFO   ] Building AMBER Ligand topology from Complex...
[INFO   ] Assigning PBRadii mbondi2 to Ligand...
[INFO   ] Writing Normal Ligand AMBER topology...
[INFO   ] Cleaning normal complex trajectories...
[INFO   ] Building AMBER topologies from GROMACS files... Done.

[INFO   ] Loading and checking parameter files for compatibility...
[INFO   ] Preparing trajectories for simulation...

[INFO   ] 10001 frames were processed by cpptraj for use in calculation.
[INFO   ] Starting calculations in 40 CPUs...

[INFO   ] Running calculations on normal system...
[INFO   ] Beginning GB calculations with /mnt/home/bhattpan/anaconda3/envs/AmberTools23/bin/sander
[INFO   ]   calculating complex contribution...
            100%|##########| 10001/10001 [elapsed: 38:44 remaining: 00:00]
[INFO   ]   calculating receptor contribution...
            100%|##########| 10001/10001 [elapsed: 38:16 remaining: 00:00]
[INFO   ]   calculating ligand contribution...
            100%|##########| 10001/10001 [elapsed: 00:00 remaining: 00:00]
[INFO   ] Parsing results to output files...

[INFO   ] Timing:
[INFO   ] Total GROMACS setup time:                   0.020 hr.
[INFO   ] Total AMBER setup time:                     0.001 hr.
[INFO   ] Creating trajectories with cpptraj:         0.105 hr.
[INFO   ] Total calculation time:                     1.323 hr.
[INFO   ] Total GB calculation time:                  1.318 hr.
[INFO   ] Statistics calculation & output writing:    0.001 hr.
[INFO   ] Total time taken:                           1.451 hr.

[INFO   ]
   Finalizing gmx_MMPBSA: [ERROR  ] = 0; [WARNING] = 0
   Check the gmx_MMPBSA.log file for more details...

[INFO   ]
 Thank you for using gmx_MMPBSA. Please consider supporting gmx_MMPBSA by citing our publication:
    Valdés-Tresanco, M.S., Valdés-Tresanco, M.E., Valiente, P.A. and Moreno E.
    gmx_MMPBSA: A New Tool to Perform End-State Free Energy Calculations with GROMACS.
    J Chem Theory Comput., 2021, 17 (10):6281-6291. Epub 2021 Sep 29. PMID: 34586825.
    https://pubs.acs.org/doi/10.1021/acs.jctc.1c00645

Also consider citing MMPBSA.py:
    Miller III, B. R., McGee Jr., T. D., Swails, J. M. Homeyer, N. Gohlke, H. and Roitberg, A. E.
    MMPBSA.py: An Efficient Program for End-State Free Energy Calculations.
    J. Chem. Theory Comput., 2012, 8 (9) pp 3314-3321

[INFO   ] Opening gmx_MMPBSA_ana to analyze results...

ERROR:root:MMPBSA_Error Could not import PyQt5/PyQt6. gmx_MMPBSA_ana will be disabled until PyQt5/PyQt6 is installed.
           Check the gmx_MMPBSA.log file to report the problem.
Traceback (most recent call last):
  File "/mnt/home/bhattpan/.local/bin/gmx_MMPBSA_ana", line 8, in <module>
    sys.exit(gmxmmpbsa_ana())
             ^^^^^^^^^^^^^^^
  File "/mnt/home/bhattpan/.local/lib/python3.11/site-packages/GMXMMPBSA/app.py", line 126, in gmxmmpbsa_ana
    GMXMMPBSA_ERROR('Could not import PyQt5/PyQt6. gmx_MMPBSA_ana will be disabled until PyQt5/PyQt6 is '
  File "/mnt/home/bhattpan/.local/lib/python3.11/site-packages/GMXMMPBSA/exceptions.py", line 169, in __init__
    raise exc(msg + '\nCheck the gmx_MMPBSA.log file to report the problem.')
GMXMMPBSA.exceptions.MMPBSA_Error: Could not import PyQt5/PyQt6. gmx_MMPBSA_ana will be disabled until PyQt5/PyQt6 is installed
Check the gmx_MMPBSA.log file to report the problem.
[ERROR  ] Unable to start gmx_MMPBSA_ana...
[INFO   ] Finalized...
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[30534,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

### Actual outcome

![image](https://github.com/user-attachments/assets/04eafad6-0f5b-44b4-808a-4d527636ac73)

### Expected outcome

as per tutorial

### gmx_MMPBSA_ana Version

(AmberTools23) bhattpan@dev-amd20-v100:/mnt/gs21/scratch/bhattpan/2p$ gmx_MMPBSA_ana -v ERROR:root:MMPBSA_Error Could not import PyQt5/PyQt6. gmx_MMPBSA_ana will be disabled until PyQt5/PyQt6 is installed.            Check the gmx_MMPBSA.log file to report the problem. Traceback (most recent call last):   File "/mnt/home/bhattpan/.local/bin/gmx_MMPBSA_ana", line 8, in <module>     sys.exit(gmxmmpbsa_ana())              ^^^^^^^^^^^^^^^   File "/mnt/home/bhattpan/.local/lib/python3.11/site-packages/GMXMMPBSA/app.py", line 126, in gmxmmpbsa_ana     GMXMMPBSA_ERROR('Could not import PyQt5/PyQt6. gmx_MMPBSA_ana will be disabled until PyQt5/PyQt6 is '   File "/mnt/home/bhattpan/.local/lib/python3.11/site-packages/GMXMMPBSA/exceptions.py", line 169, in __init__     raise exc(msg + '\nCheck the gmx_MMPBSA.log file to report the problem.') GMXMMPBSA.exceptions.MMPBSA_Error: Could not import PyQt5/PyQt6. gmx_MMPBSA_ana will be disabled until PyQt5/PyQt6 is installed Check the gmx_MMPBSA.log file to report the problem. (AmberTools23) bhattpan@dev-amd20-v100:/mnt/gs21/scratch/bhattpan/2p$ gmx_MMPBSA_ana -v ERROR:root:MMPBSA_Error Could not import PyQt5/PyQt6. gmx_MMPBSA_ana will be disabled until PyQt5/PyQt6 is installed.            Check the gmx_MMPBSA.log file to report the problem. Traceback (most recent call last):   File "/mnt/home/bhattpan/.local/bin/gmx_MMPBSA_ana", line 8, in <module>     sys.exit(gmxmmpbsa_ana())              ^^^^^^^^^^^^^^^   File "/mnt/home/bhattpan/.local/lib/python3.11/site-packages/GMXMMPBSA/app.py", line 126, in gmxmmpbsa_ana     GMXMMPBSA_ERROR('Could not import PyQt5/PyQt6. gmx_MMPBSA_ana will be disabled until PyQt5/PyQt6 is '   File "/mnt/home/bhattpan/.local/lib/python3.11/site-packages/GMXMMPBSA/exceptions.py", line 169, in __init__     raise exc(msg + '\nCheck the gmx_MMPBSA.log file to report the problem.') GMXMMPBSA.exceptions.MMPBSA_Error: Could not import PyQt5/PyQt6. gmx_MMPBSA_ana will be disabled until PyQt5/PyQt6 is installed Check the gmx_MMPBSA.log file to report the problem. (AmberTools23) bhattpan@dev-amd20-v100:/mnt/gs21/scratch/bhattpan/2p$

### Python version

Python 3.11.5

### Installation

AmberTools compilation + pip

**Comment by Valdes-Tresanco-MS** [comment]
This error occurs because you do not have the PyQt library installed and gmx_MMPBSA tries to run gmx_MMPBSA_ana after finishing the calculations.
- If you want to open gmx_MMPBSA_ana after the calculations and you have a graphic driver (this does not work in HPC or WSL without graphic drivers)
You should install PyQt6 `python—m pip install pyqt6` or PyQt5 `python—m pip install pyqt5`.
- To avoid opening gmx_MMPBSA_ana after the calculation use the option `-nogui`
