### ISSUE TITLE
Suddenly gmx_MMPBSA_ana stoped working

### ISSUE THREAD

**Issue by debanjansen48** [Valdes-Tresanco-MS/gmx_MMPBSA#75]
That module was working nicely. Suddenly it started to through an error given bellow

-mmpbsa$ gmx_MMPBSA_ana 
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/lab1/Amber/amber20/miniconda/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/lab1/Amber/amber20/miniconda/lib/python3.9/site-packages/GMXMMPBSA/analyzer/utils.py", line 33, in calculatestar
    return run_process(*args)
  File "/home/lab1/Amber/amber20/miniconda/lib/python3.9/site-packages/GMXMMPBSA/analyzer/utils.py", line 37, in run_process
    results = func(path)
  File "/home/lab1/Amber/amber20/miniconda/lib/python3.9/site-packages/GMXMMPBSA/API.py", line 492, in load_gmxmmpbsa_info
    return_data['decomp']['gb']['complex'] = DecompClass(app.FILES.prefix + 'complex_gb.mdout',
  File "/home/lab1/Amber/amber20/miniconda/lib/python3.9/site-packages/GMXMMPBSA/API.py", line 484, in <lambda>
    DecompClass = lambda x, part: APIDecompOut(x, part, app)
  File "/home/lab1/Amber/amber20/miniconda/lib/python3.9/site-packages/GMXMMPBSA/API.py", line 213, in __init__
    rnum, internal, vdw, eel, pol, sas, tot = self.get_next_term(key)
  File "/home/lab1/Amber/amber20/miniconda/lib/python3.9/site-packages/GMXMMPBSA/amber_outputs.py", line 1596, in _get_next_term
    internal = float(line[11:20])
ValueError: could not convert string to float: '*********'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lab1/Amber/amber20/miniconda/lib/python3.9/site-packages/GMXMMPBSA/analyzer/utils.py", line 61, in run
    for result in imap_unordered_it:
  File "/home/lab1/Amber/amber20/miniconda/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
ValueError: could not convert string to float: '*********'
Aborted (core dumped)

**Comment by Valdes-Tresanco-MS** [comment]
Chech this [Q&A](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/Q%26A/calculations/#possible-solutions)

**Comment by debanjansen48** [comment]
ok..thanks..
